// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_detectedtrafficlight.proto

#ifndef PROTOBUF_osi_5fdetectedtrafficlight_2eproto__INCLUDED
#define PROTOBUF_osi_5fdetectedtrafficlight_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "osi_common.pb.h"
#include "osi_trafficlight.pb.h"
#include "osi_detectedobject.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_osi_5fdetectedtrafficlight_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsDetectedTrafficLight_CandidateTrafficLightImpl();
void InitDefaultsDetectedTrafficLight_CandidateTrafficLight();
void InitDefaultsDetectedTrafficLightImpl();
void InitDefaultsDetectedTrafficLight();
inline void InitDefaults() {
  InitDefaultsDetectedTrafficLight_CandidateTrafficLight();
  InitDefaultsDetectedTrafficLight();
}
}  // namespace protobuf_osi_5fdetectedtrafficlight_2eproto
namespace osi3 {
class DetectedTrafficLight;
class DetectedTrafficLightDefaultTypeInternal;
extern DetectedTrafficLightDefaultTypeInternal _DetectedTrafficLight_default_instance_;
class DetectedTrafficLight_CandidateTrafficLight;
class DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal;
extern DetectedTrafficLight_CandidateTrafficLightDefaultTypeInternal _DetectedTrafficLight_CandidateTrafficLight_default_instance_;
}  // namespace osi3
namespace osi3 {

// ===================================================================

class DetectedTrafficLight_CandidateTrafficLight : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.DetectedTrafficLight.CandidateTrafficLight) */ {
 public:
  DetectedTrafficLight_CandidateTrafficLight();
  virtual ~DetectedTrafficLight_CandidateTrafficLight();

  DetectedTrafficLight_CandidateTrafficLight(const DetectedTrafficLight_CandidateTrafficLight& from);

  inline DetectedTrafficLight_CandidateTrafficLight& operator=(const DetectedTrafficLight_CandidateTrafficLight& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetectedTrafficLight_CandidateTrafficLight(DetectedTrafficLight_CandidateTrafficLight&& from) noexcept
    : DetectedTrafficLight_CandidateTrafficLight() {
    *this = ::std::move(from);
  }

  inline DetectedTrafficLight_CandidateTrafficLight& operator=(DetectedTrafficLight_CandidateTrafficLight&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DetectedTrafficLight_CandidateTrafficLight& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectedTrafficLight_CandidateTrafficLight* internal_default_instance() {
    return reinterpret_cast<const DetectedTrafficLight_CandidateTrafficLight*>(
               &_DetectedTrafficLight_CandidateTrafficLight_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(DetectedTrafficLight_CandidateTrafficLight* other);
  friend void swap(DetectedTrafficLight_CandidateTrafficLight& a, DetectedTrafficLight_CandidateTrafficLight& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetectedTrafficLight_CandidateTrafficLight* New() const PROTOBUF_FINAL { return New(NULL); }

  DetectedTrafficLight_CandidateTrafficLight* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DetectedTrafficLight_CandidateTrafficLight& from);
  void MergeFrom(const DetectedTrafficLight_CandidateTrafficLight& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DetectedTrafficLight_CandidateTrafficLight* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .osi3.TrafficLight.Classification classification = 2;
  bool has_classification() const;
  void clear_classification();
  static const int kClassificationFieldNumber = 2;
  const ::osi3::TrafficLight_Classification& classification() const;
  ::osi3::TrafficLight_Classification* release_classification();
  ::osi3::TrafficLight_Classification* mutable_classification();
  void set_allocated_classification(::osi3::TrafficLight_Classification* classification);

  // double probability = 1;
  void clear_probability();
  static const int kProbabilityFieldNumber = 1;
  double probability() const;
  void set_probability(double value);

  // @@protoc_insertion_point(class_scope:osi3.DetectedTrafficLight.CandidateTrafficLight)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::osi3::TrafficLight_Classification* classification_;
  double probability_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fdetectedtrafficlight_2eproto::TableStruct;
  friend void ::protobuf_osi_5fdetectedtrafficlight_2eproto::InitDefaultsDetectedTrafficLight_CandidateTrafficLightImpl();
};
// -------------------------------------------------------------------

class DetectedTrafficLight : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.DetectedTrafficLight) */ {
 public:
  DetectedTrafficLight();
  virtual ~DetectedTrafficLight();

  DetectedTrafficLight(const DetectedTrafficLight& from);

  inline DetectedTrafficLight& operator=(const DetectedTrafficLight& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  DetectedTrafficLight(DetectedTrafficLight&& from) noexcept
    : DetectedTrafficLight() {
    *this = ::std::move(from);
  }

  inline DetectedTrafficLight& operator=(DetectedTrafficLight&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const DetectedTrafficLight& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const DetectedTrafficLight* internal_default_instance() {
    return reinterpret_cast<const DetectedTrafficLight*>(
               &_DetectedTrafficLight_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(DetectedTrafficLight* other);
  friend void swap(DetectedTrafficLight& a, DetectedTrafficLight& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline DetectedTrafficLight* New() const PROTOBUF_FINAL { return New(NULL); }

  DetectedTrafficLight* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const DetectedTrafficLight& from);
  void MergeFrom(const DetectedTrafficLight& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(DetectedTrafficLight* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef DetectedTrafficLight_CandidateTrafficLight CandidateTrafficLight;

  // accessors -------------------------------------------------------

  // repeated .osi3.DetectedTrafficLight.CandidateTrafficLight candidate = 4;
  int candidate_size() const;
  void clear_candidate();
  static const int kCandidateFieldNumber = 4;
  const ::osi3::DetectedTrafficLight_CandidateTrafficLight& candidate(int index) const;
  ::osi3::DetectedTrafficLight_CandidateTrafficLight* mutable_candidate(int index);
  ::osi3::DetectedTrafficLight_CandidateTrafficLight* add_candidate();
  ::google::protobuf::RepeatedPtrField< ::osi3::DetectedTrafficLight_CandidateTrafficLight >*
      mutable_candidate();
  const ::google::protobuf::RepeatedPtrField< ::osi3::DetectedTrafficLight_CandidateTrafficLight >&
      candidate() const;

  // .osi3.DetectedItemHeader header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::osi3::DetectedItemHeader& header() const;
  ::osi3::DetectedItemHeader* release_header();
  ::osi3::DetectedItemHeader* mutable_header();
  void set_allocated_header(::osi3::DetectedItemHeader* header);

  // .osi3.BaseStationary base = 2;
  bool has_base() const;
  void clear_base();
  static const int kBaseFieldNumber = 2;
  const ::osi3::BaseStationary& base() const;
  ::osi3::BaseStationary* release_base();
  ::osi3::BaseStationary* mutable_base();
  void set_allocated_base(::osi3::BaseStationary* base);

  // .osi3.BaseStationary base_rmse = 3;
  bool has_base_rmse() const;
  void clear_base_rmse();
  static const int kBaseRmseFieldNumber = 3;
  const ::osi3::BaseStationary& base_rmse() const;
  ::osi3::BaseStationary* release_base_rmse();
  ::osi3::BaseStationary* mutable_base_rmse();
  void set_allocated_base_rmse(::osi3::BaseStationary* base_rmse);

  // @@protoc_insertion_point(class_scope:osi3.DetectedTrafficLight)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::osi3::DetectedTrafficLight_CandidateTrafficLight > candidate_;
  ::osi3::DetectedItemHeader* header_;
  ::osi3::BaseStationary* base_;
  ::osi3::BaseStationary* base_rmse_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fdetectedtrafficlight_2eproto::TableStruct;
  friend void ::protobuf_osi_5fdetectedtrafficlight_2eproto::InitDefaultsDetectedTrafficLightImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// DetectedTrafficLight_CandidateTrafficLight

// double probability = 1;
inline void DetectedTrafficLight_CandidateTrafficLight::clear_probability() {
  probability_ = 0;
}
inline double DetectedTrafficLight_CandidateTrafficLight::probability() const {
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.CandidateTrafficLight.probability)
  return probability_;
}
inline void DetectedTrafficLight_CandidateTrafficLight::set_probability(double value) {
  
  probability_ = value;
  // @@protoc_insertion_point(field_set:osi3.DetectedTrafficLight.CandidateTrafficLight.probability)
}

// .osi3.TrafficLight.Classification classification = 2;
inline bool DetectedTrafficLight_CandidateTrafficLight::has_classification() const {
  return this != internal_default_instance() && classification_ != NULL;
}
inline const ::osi3::TrafficLight_Classification& DetectedTrafficLight_CandidateTrafficLight::classification() const {
  const ::osi3::TrafficLight_Classification* p = classification_;
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.CandidateTrafficLight.classification)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::TrafficLight_Classification*>(
      &::osi3::_TrafficLight_Classification_default_instance_);
}
inline ::osi3::TrafficLight_Classification* DetectedTrafficLight_CandidateTrafficLight::release_classification() {
  // @@protoc_insertion_point(field_release:osi3.DetectedTrafficLight.CandidateTrafficLight.classification)
  
  ::osi3::TrafficLight_Classification* temp = classification_;
  classification_ = NULL;
  return temp;
}
inline ::osi3::TrafficLight_Classification* DetectedTrafficLight_CandidateTrafficLight::mutable_classification() {
  
  if (classification_ == NULL) {
    classification_ = new ::osi3::TrafficLight_Classification;
  }
  // @@protoc_insertion_point(field_mutable:osi3.DetectedTrafficLight.CandidateTrafficLight.classification)
  return classification_;
}
inline void DetectedTrafficLight_CandidateTrafficLight::set_allocated_classification(::osi3::TrafficLight_Classification* classification) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(classification_);
  }
  if (classification) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      classification = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, classification, submessage_arena);
    }
    
  } else {
    
  }
  classification_ = classification;
  // @@protoc_insertion_point(field_set_allocated:osi3.DetectedTrafficLight.CandidateTrafficLight.classification)
}

// -------------------------------------------------------------------

// DetectedTrafficLight

// .osi3.DetectedItemHeader header = 1;
inline bool DetectedTrafficLight::has_header() const {
  return this != internal_default_instance() && header_ != NULL;
}
inline const ::osi3::DetectedItemHeader& DetectedTrafficLight::header() const {
  const ::osi3::DetectedItemHeader* p = header_;
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.header)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::DetectedItemHeader*>(
      &::osi3::_DetectedItemHeader_default_instance_);
}
inline ::osi3::DetectedItemHeader* DetectedTrafficLight::release_header() {
  // @@protoc_insertion_point(field_release:osi3.DetectedTrafficLight.header)
  
  ::osi3::DetectedItemHeader* temp = header_;
  header_ = NULL;
  return temp;
}
inline ::osi3::DetectedItemHeader* DetectedTrafficLight::mutable_header() {
  
  if (header_ == NULL) {
    header_ = new ::osi3::DetectedItemHeader;
  }
  // @@protoc_insertion_point(field_mutable:osi3.DetectedTrafficLight.header)
  return header_;
}
inline void DetectedTrafficLight::set_allocated_header(::osi3::DetectedItemHeader* header) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(header_);
  }
  if (header) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      header = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, header, submessage_arena);
    }
    
  } else {
    
  }
  header_ = header;
  // @@protoc_insertion_point(field_set_allocated:osi3.DetectedTrafficLight.header)
}

// .osi3.BaseStationary base = 2;
inline bool DetectedTrafficLight::has_base() const {
  return this != internal_default_instance() && base_ != NULL;
}
inline const ::osi3::BaseStationary& DetectedTrafficLight::base() const {
  const ::osi3::BaseStationary* p = base_;
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.base)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::BaseStationary*>(
      &::osi3::_BaseStationary_default_instance_);
}
inline ::osi3::BaseStationary* DetectedTrafficLight::release_base() {
  // @@protoc_insertion_point(field_release:osi3.DetectedTrafficLight.base)
  
  ::osi3::BaseStationary* temp = base_;
  base_ = NULL;
  return temp;
}
inline ::osi3::BaseStationary* DetectedTrafficLight::mutable_base() {
  
  if (base_ == NULL) {
    base_ = new ::osi3::BaseStationary;
  }
  // @@protoc_insertion_point(field_mutable:osi3.DetectedTrafficLight.base)
  return base_;
}
inline void DetectedTrafficLight::set_allocated_base(::osi3::BaseStationary* base) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(base_);
  }
  if (base) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      base = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  base_ = base;
  // @@protoc_insertion_point(field_set_allocated:osi3.DetectedTrafficLight.base)
}

// .osi3.BaseStationary base_rmse = 3;
inline bool DetectedTrafficLight::has_base_rmse() const {
  return this != internal_default_instance() && base_rmse_ != NULL;
}
inline const ::osi3::BaseStationary& DetectedTrafficLight::base_rmse() const {
  const ::osi3::BaseStationary* p = base_rmse_;
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.base_rmse)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::BaseStationary*>(
      &::osi3::_BaseStationary_default_instance_);
}
inline ::osi3::BaseStationary* DetectedTrafficLight::release_base_rmse() {
  // @@protoc_insertion_point(field_release:osi3.DetectedTrafficLight.base_rmse)
  
  ::osi3::BaseStationary* temp = base_rmse_;
  base_rmse_ = NULL;
  return temp;
}
inline ::osi3::BaseStationary* DetectedTrafficLight::mutable_base_rmse() {
  
  if (base_rmse_ == NULL) {
    base_rmse_ = new ::osi3::BaseStationary;
  }
  // @@protoc_insertion_point(field_mutable:osi3.DetectedTrafficLight.base_rmse)
  return base_rmse_;
}
inline void DetectedTrafficLight::set_allocated_base_rmse(::osi3::BaseStationary* base_rmse) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(base_rmse_);
  }
  if (base_rmse) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      base_rmse = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, base_rmse, submessage_arena);
    }
    
  } else {
    
  }
  base_rmse_ = base_rmse;
  // @@protoc_insertion_point(field_set_allocated:osi3.DetectedTrafficLight.base_rmse)
}

// repeated .osi3.DetectedTrafficLight.CandidateTrafficLight candidate = 4;
inline int DetectedTrafficLight::candidate_size() const {
  return candidate_.size();
}
inline void DetectedTrafficLight::clear_candidate() {
  candidate_.Clear();
}
inline const ::osi3::DetectedTrafficLight_CandidateTrafficLight& DetectedTrafficLight::candidate(int index) const {
  // @@protoc_insertion_point(field_get:osi3.DetectedTrafficLight.candidate)
  return candidate_.Get(index);
}
inline ::osi3::DetectedTrafficLight_CandidateTrafficLight* DetectedTrafficLight::mutable_candidate(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.DetectedTrafficLight.candidate)
  return candidate_.Mutable(index);
}
inline ::osi3::DetectedTrafficLight_CandidateTrafficLight* DetectedTrafficLight::add_candidate() {
  // @@protoc_insertion_point(field_add:osi3.DetectedTrafficLight.candidate)
  return candidate_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::DetectedTrafficLight_CandidateTrafficLight >*
DetectedTrafficLight::mutable_candidate() {
  // @@protoc_insertion_point(field_mutable_list:osi3.DetectedTrafficLight.candidate)
  return &candidate_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::DetectedTrafficLight_CandidateTrafficLight >&
DetectedTrafficLight::candidate() const {
  // @@protoc_insertion_point(field_list:osi3.DetectedTrafficLight.candidate)
  return candidate_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osi3

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_osi_5fdetectedtrafficlight_2eproto__INCLUDED
