// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_detectedroadmarking.proto

#include "osi_detectedroadmarking.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace osi3 {
class DetectedRoadMarking_CandidateRoadMarkingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DetectedRoadMarking_CandidateRoadMarking>
      _instance;
} _DetectedRoadMarking_CandidateRoadMarking_default_instance_;
class DetectedRoadMarkingDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<DetectedRoadMarking>
      _instance;
} _DetectedRoadMarking_default_instance_;
}  // namespace osi3
namespace protobuf_osi_5fdetectedroadmarking_2eproto {
void InitDefaultsDetectedRoadMarking_CandidateRoadMarkingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_osi_5froadmarking_2eproto::InitDefaultsRoadMarking_Classification();
  {
    void* ptr = &::osi3::_DetectedRoadMarking_CandidateRoadMarking_default_instance_;
    new (ptr) ::osi3::DetectedRoadMarking_CandidateRoadMarking();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::osi3::DetectedRoadMarking_CandidateRoadMarking::InitAsDefaultInstance();
}

void InitDefaultsDetectedRoadMarking_CandidateRoadMarking() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsDetectedRoadMarking_CandidateRoadMarkingImpl);
}

void InitDefaultsDetectedRoadMarkingImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  protobuf_osi_5fdetectedobject_2eproto::InitDefaultsDetectedItemHeader();
  protobuf_osi_5fcommon_2eproto::InitDefaultsBaseStationary();
  protobuf_osi_5fdetectedroadmarking_2eproto::InitDefaultsDetectedRoadMarking_CandidateRoadMarking();
  {
    void* ptr = &::osi3::_DetectedRoadMarking_default_instance_;
    new (ptr) ::osi3::DetectedRoadMarking();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::osi3::DetectedRoadMarking::InitAsDefaultInstance();
}

void InitDefaultsDetectedRoadMarking() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsDetectedRoadMarkingImpl);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking_CandidateRoadMarking, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking_CandidateRoadMarking, probability_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking_CandidateRoadMarking, classification_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking, header_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking, base_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking, base_rmse_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::osi3::DetectedRoadMarking, candidate_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::osi3::DetectedRoadMarking_CandidateRoadMarking)},
  { 7, -1, sizeof(::osi3::DetectedRoadMarking)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::osi3::_DetectedRoadMarking_CandidateRoadMarking_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::osi3::_DetectedRoadMarking_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "osi_detectedroadmarking.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\035osi_detectedroadmarking.proto\022\004osi3\032\020o"
      "si_common.proto\032\025osi_roadmarking.proto\032\030"
      "osi_detectedobject.proto\"\266\002\n\023DetectedRoa"
      "dMarking\022(\n\006header\030\001 \001(\0132\030.osi3.Detected"
      "ItemHeader\022\"\n\004base\030\002 \001(\0132\024.osi3.BaseStat"
      "ionary\022\'\n\tbase_rmse\030\003 \001(\0132\024.osi3.BaseSta"
      "tionary\022A\n\tcandidate\030\004 \003(\0132..osi3.Detect"
      "edRoadMarking.CandidateRoadMarking\032e\n\024Ca"
      "ndidateRoadMarking\022\023\n\013probability\030\001 \001(\001\022"
      "8\n\016classification\030\002 \001(\0132 .osi3.RoadMarki"
      "ng.ClassificationB\002H\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 429);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "osi_detectedroadmarking.proto", &protobuf_RegisterTypes);
  ::protobuf_osi_5fcommon_2eproto::AddDescriptors();
  ::protobuf_osi_5froadmarking_2eproto::AddDescriptors();
  ::protobuf_osi_5fdetectedobject_2eproto::AddDescriptors();
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_osi_5fdetectedroadmarking_2eproto
namespace osi3 {

// ===================================================================

void DetectedRoadMarking_CandidateRoadMarking::InitAsDefaultInstance() {
  ::osi3::_DetectedRoadMarking_CandidateRoadMarking_default_instance_._instance.get_mutable()->classification_ = const_cast< ::osi3::RoadMarking_Classification*>(
      ::osi3::RoadMarking_Classification::internal_default_instance());
}
void DetectedRoadMarking_CandidateRoadMarking::clear_classification() {
  if (GetArenaNoVirtual() == NULL && classification_ != NULL) {
    delete classification_;
  }
  classification_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DetectedRoadMarking_CandidateRoadMarking::kProbabilityFieldNumber;
const int DetectedRoadMarking_CandidateRoadMarking::kClassificationFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DetectedRoadMarking_CandidateRoadMarking::DetectedRoadMarking_CandidateRoadMarking()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_osi_5fdetectedroadmarking_2eproto::InitDefaultsDetectedRoadMarking_CandidateRoadMarking();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:osi3.DetectedRoadMarking.CandidateRoadMarking)
}
DetectedRoadMarking_CandidateRoadMarking::DetectedRoadMarking_CandidateRoadMarking(const DetectedRoadMarking_CandidateRoadMarking& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_classification()) {
    classification_ = new ::osi3::RoadMarking_Classification(*from.classification_);
  } else {
    classification_ = NULL;
  }
  probability_ = from.probability_;
  // @@protoc_insertion_point(copy_constructor:osi3.DetectedRoadMarking.CandidateRoadMarking)
}

void DetectedRoadMarking_CandidateRoadMarking::SharedCtor() {
  ::memset(&classification_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&probability_) -
      reinterpret_cast<char*>(&classification_)) + sizeof(probability_));
  _cached_size_ = 0;
}

DetectedRoadMarking_CandidateRoadMarking::~DetectedRoadMarking_CandidateRoadMarking() {
  // @@protoc_insertion_point(destructor:osi3.DetectedRoadMarking.CandidateRoadMarking)
  SharedDtor();
}

void DetectedRoadMarking_CandidateRoadMarking::SharedDtor() {
  if (this != internal_default_instance()) delete classification_;
}

void DetectedRoadMarking_CandidateRoadMarking::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DetectedRoadMarking_CandidateRoadMarking::descriptor() {
  ::protobuf_osi_5fdetectedroadmarking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_osi_5fdetectedroadmarking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DetectedRoadMarking_CandidateRoadMarking& DetectedRoadMarking_CandidateRoadMarking::default_instance() {
  ::protobuf_osi_5fdetectedroadmarking_2eproto::InitDefaultsDetectedRoadMarking_CandidateRoadMarking();
  return *internal_default_instance();
}

DetectedRoadMarking_CandidateRoadMarking* DetectedRoadMarking_CandidateRoadMarking::New(::google::protobuf::Arena* arena) const {
  DetectedRoadMarking_CandidateRoadMarking* n = new DetectedRoadMarking_CandidateRoadMarking;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DetectedRoadMarking_CandidateRoadMarking::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && classification_ != NULL) {
    delete classification_;
  }
  classification_ = NULL;
  probability_ = 0;
  _internal_metadata_.Clear();
}

bool DetectedRoadMarking_CandidateRoadMarking::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // double probability = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(9u /* 9 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   double, ::google::protobuf::internal::WireFormatLite::TYPE_DOUBLE>(
                 input, &probability_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .osi3.RoadMarking.Classification classification = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_classification()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:osi3.DetectedRoadMarking.CandidateRoadMarking)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:osi3.DetectedRoadMarking.CandidateRoadMarking)
  return false;
#undef DO_
}

void DetectedRoadMarking_CandidateRoadMarking::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double probability = 1;
  if (this->probability() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteDouble(1, this->probability(), output);
  }

  // .osi3.RoadMarking.Classification classification = 2;
  if (this->has_classification()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->classification_, output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:osi3.DetectedRoadMarking.CandidateRoadMarking)
}

::google::protobuf::uint8* DetectedRoadMarking_CandidateRoadMarking::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // double probability = 1;
  if (this->probability() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteDoubleToArray(1, this->probability(), target);
  }

  // .osi3.RoadMarking.Classification classification = 2;
  if (this->has_classification()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->classification_, deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.DetectedRoadMarking.CandidateRoadMarking)
  return target;
}

size_t DetectedRoadMarking_CandidateRoadMarking::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .osi3.RoadMarking.Classification classification = 2;
  if (this->has_classification()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->classification_);
  }

  // double probability = 1;
  if (this->probability() != 0) {
    total_size += 1 + 8;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DetectedRoadMarking_CandidateRoadMarking::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectedRoadMarking_CandidateRoadMarking* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DetectedRoadMarking_CandidateRoadMarking>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:osi3.DetectedRoadMarking.CandidateRoadMarking)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:osi3.DetectedRoadMarking.CandidateRoadMarking)
    MergeFrom(*source);
  }
}

void DetectedRoadMarking_CandidateRoadMarking::MergeFrom(const DetectedRoadMarking_CandidateRoadMarking& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_classification()) {
    mutable_classification()->::osi3::RoadMarking_Classification::MergeFrom(from.classification());
  }
  if (from.probability() != 0) {
    set_probability(from.probability());
  }
}

void DetectedRoadMarking_CandidateRoadMarking::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectedRoadMarking_CandidateRoadMarking::CopyFrom(const DetectedRoadMarking_CandidateRoadMarking& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.DetectedRoadMarking.CandidateRoadMarking)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectedRoadMarking_CandidateRoadMarking::IsInitialized() const {
  return true;
}

void DetectedRoadMarking_CandidateRoadMarking::Swap(DetectedRoadMarking_CandidateRoadMarking* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DetectedRoadMarking_CandidateRoadMarking::InternalSwap(DetectedRoadMarking_CandidateRoadMarking* other) {
  using std::swap;
  swap(classification_, other->classification_);
  swap(probability_, other->probability_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DetectedRoadMarking_CandidateRoadMarking::GetMetadata() const {
  protobuf_osi_5fdetectedroadmarking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_osi_5fdetectedroadmarking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void DetectedRoadMarking::InitAsDefaultInstance() {
  ::osi3::_DetectedRoadMarking_default_instance_._instance.get_mutable()->header_ = const_cast< ::osi3::DetectedItemHeader*>(
      ::osi3::DetectedItemHeader::internal_default_instance());
  ::osi3::_DetectedRoadMarking_default_instance_._instance.get_mutable()->base_ = const_cast< ::osi3::BaseStationary*>(
      ::osi3::BaseStationary::internal_default_instance());
  ::osi3::_DetectedRoadMarking_default_instance_._instance.get_mutable()->base_rmse_ = const_cast< ::osi3::BaseStationary*>(
      ::osi3::BaseStationary::internal_default_instance());
}
void DetectedRoadMarking::clear_header() {
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
}
void DetectedRoadMarking::clear_base() {
  if (GetArenaNoVirtual() == NULL && base_ != NULL) {
    delete base_;
  }
  base_ = NULL;
}
void DetectedRoadMarking::clear_base_rmse() {
  if (GetArenaNoVirtual() == NULL && base_rmse_ != NULL) {
    delete base_rmse_;
  }
  base_rmse_ = NULL;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int DetectedRoadMarking::kHeaderFieldNumber;
const int DetectedRoadMarking::kBaseFieldNumber;
const int DetectedRoadMarking::kBaseRmseFieldNumber;
const int DetectedRoadMarking::kCandidateFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

DetectedRoadMarking::DetectedRoadMarking()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_osi_5fdetectedroadmarking_2eproto::InitDefaultsDetectedRoadMarking();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:osi3.DetectedRoadMarking)
}
DetectedRoadMarking::DetectedRoadMarking(const DetectedRoadMarking& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      candidate_(from.candidate_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_header()) {
    header_ = new ::osi3::DetectedItemHeader(*from.header_);
  } else {
    header_ = NULL;
  }
  if (from.has_base()) {
    base_ = new ::osi3::BaseStationary(*from.base_);
  } else {
    base_ = NULL;
  }
  if (from.has_base_rmse()) {
    base_rmse_ = new ::osi3::BaseStationary(*from.base_rmse_);
  } else {
    base_rmse_ = NULL;
  }
  // @@protoc_insertion_point(copy_constructor:osi3.DetectedRoadMarking)
}

void DetectedRoadMarking::SharedCtor() {
  ::memset(&header_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&base_rmse_) -
      reinterpret_cast<char*>(&header_)) + sizeof(base_rmse_));
  _cached_size_ = 0;
}

DetectedRoadMarking::~DetectedRoadMarking() {
  // @@protoc_insertion_point(destructor:osi3.DetectedRoadMarking)
  SharedDtor();
}

void DetectedRoadMarking::SharedDtor() {
  if (this != internal_default_instance()) delete header_;
  if (this != internal_default_instance()) delete base_;
  if (this != internal_default_instance()) delete base_rmse_;
}

void DetectedRoadMarking::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* DetectedRoadMarking::descriptor() {
  ::protobuf_osi_5fdetectedroadmarking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_osi_5fdetectedroadmarking_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const DetectedRoadMarking& DetectedRoadMarking::default_instance() {
  ::protobuf_osi_5fdetectedroadmarking_2eproto::InitDefaultsDetectedRoadMarking();
  return *internal_default_instance();
}

DetectedRoadMarking* DetectedRoadMarking::New(::google::protobuf::Arena* arena) const {
  DetectedRoadMarking* n = new DetectedRoadMarking;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void DetectedRoadMarking::Clear() {
// @@protoc_insertion_point(message_clear_start:osi3.DetectedRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  candidate_.Clear();
  if (GetArenaNoVirtual() == NULL && header_ != NULL) {
    delete header_;
  }
  header_ = NULL;
  if (GetArenaNoVirtual() == NULL && base_ != NULL) {
    delete base_;
  }
  base_ = NULL;
  if (GetArenaNoVirtual() == NULL && base_rmse_ != NULL) {
    delete base_rmse_;
  }
  base_rmse_ = NULL;
  _internal_metadata_.Clear();
}

bool DetectedRoadMarking::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:osi3.DetectedRoadMarking)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .osi3.DetectedItemHeader header = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_header()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .osi3.BaseStationary base = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_base()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .osi3.BaseStationary base_rmse = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_base_rmse()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .osi3.DetectedRoadMarking.CandidateRoadMarking candidate = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(input, add_candidate()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:osi3.DetectedRoadMarking)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:osi3.DetectedRoadMarking)
  return false;
#undef DO_
}

void DetectedRoadMarking::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:osi3.DetectedRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.DetectedItemHeader header = 1;
  if (this->has_header()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->header_, output);
  }

  // .osi3.BaseStationary base = 2;
  if (this->has_base()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->base_, output);
  }

  // .osi3.BaseStationary base_rmse = 3;
  if (this->has_base_rmse()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->base_rmse_, output);
  }

  // repeated .osi3.DetectedRoadMarking.CandidateRoadMarking candidate = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->candidate_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      4, this->candidate(static_cast<int>(i)), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:osi3.DetectedRoadMarking)
}

::google::protobuf::uint8* DetectedRoadMarking::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:osi3.DetectedRoadMarking)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .osi3.DetectedItemHeader header = 1;
  if (this->has_header()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, *this->header_, deterministic, target);
  }

  // .osi3.BaseStationary base = 2;
  if (this->has_base()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, *this->base_, deterministic, target);
  }

  // .osi3.BaseStationary base_rmse = 3;
  if (this->has_base_rmse()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        3, *this->base_rmse_, deterministic, target);
  }

  // repeated .osi3.DetectedRoadMarking.CandidateRoadMarking candidate = 4;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->candidate_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        4, this->candidate(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:osi3.DetectedRoadMarking)
  return target;
}

size_t DetectedRoadMarking::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:osi3.DetectedRoadMarking)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .osi3.DetectedRoadMarking.CandidateRoadMarking candidate = 4;
  {
    unsigned int count = static_cast<unsigned int>(this->candidate_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->candidate(static_cast<int>(i)));
    }
  }

  // .osi3.DetectedItemHeader header = 1;
  if (this->has_header()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->header_);
  }

  // .osi3.BaseStationary base = 2;
  if (this->has_base()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->base_);
  }

  // .osi3.BaseStationary base_rmse = 3;
  if (this->has_base_rmse()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *this->base_rmse_);
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void DetectedRoadMarking::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:osi3.DetectedRoadMarking)
  GOOGLE_DCHECK_NE(&from, this);
  const DetectedRoadMarking* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const DetectedRoadMarking>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:osi3.DetectedRoadMarking)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:osi3.DetectedRoadMarking)
    MergeFrom(*source);
  }
}

void DetectedRoadMarking::MergeFrom(const DetectedRoadMarking& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:osi3.DetectedRoadMarking)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  candidate_.MergeFrom(from.candidate_);
  if (from.has_header()) {
    mutable_header()->::osi3::DetectedItemHeader::MergeFrom(from.header());
  }
  if (from.has_base()) {
    mutable_base()->::osi3::BaseStationary::MergeFrom(from.base());
  }
  if (from.has_base_rmse()) {
    mutable_base_rmse()->::osi3::BaseStationary::MergeFrom(from.base_rmse());
  }
}

void DetectedRoadMarking::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:osi3.DetectedRoadMarking)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void DetectedRoadMarking::CopyFrom(const DetectedRoadMarking& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:osi3.DetectedRoadMarking)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool DetectedRoadMarking::IsInitialized() const {
  return true;
}

void DetectedRoadMarking::Swap(DetectedRoadMarking* other) {
  if (other == this) return;
  InternalSwap(other);
}
void DetectedRoadMarking::InternalSwap(DetectedRoadMarking* other) {
  using std::swap;
  candidate_.InternalSwap(&other->candidate_);
  swap(header_, other->header_);
  swap(base_, other->base_);
  swap(base_rmse_, other->base_rmse_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata DetectedRoadMarking::GetMetadata() const {
  protobuf_osi_5fdetectedroadmarking_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_osi_5fdetectedroadmarking_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace osi3

// @@protoc_insertion_point(global_scope)
