// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_sensorview.proto

#ifndef PROTOBUF_osi_5fsensorview_2eproto__INCLUDED
#define PROTOBUF_osi_5fsensorview_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "osi_version.pb.h"
#include "osi_common.pb.h"
#include "osi_groundtruth.pb.h"
#include "osi_sensorviewconfiguration.pb.h"
#include "osi_hostvehicledata.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_osi_5fsensorview_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[8];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSensorViewImpl();
void InitDefaultsSensorView();
void InitDefaultsGenericSensorViewImpl();
void InitDefaultsGenericSensorView();
void InitDefaultsRadarSensorView_ReflectionImpl();
void InitDefaultsRadarSensorView_Reflection();
void InitDefaultsRadarSensorViewImpl();
void InitDefaultsRadarSensorView();
void InitDefaultsLidarSensorView_ReflectionImpl();
void InitDefaultsLidarSensorView_Reflection();
void InitDefaultsLidarSensorViewImpl();
void InitDefaultsLidarSensorView();
void InitDefaultsCameraSensorViewImpl();
void InitDefaultsCameraSensorView();
void InitDefaultsUltrasonicSensorViewImpl();
void InitDefaultsUltrasonicSensorView();
inline void InitDefaults() {
  InitDefaultsSensorView();
  InitDefaultsGenericSensorView();
  InitDefaultsRadarSensorView_Reflection();
  InitDefaultsRadarSensorView();
  InitDefaultsLidarSensorView_Reflection();
  InitDefaultsLidarSensorView();
  InitDefaultsCameraSensorView();
  InitDefaultsUltrasonicSensorView();
}
}  // namespace protobuf_osi_5fsensorview_2eproto
namespace osi3 {
class CameraSensorView;
class CameraSensorViewDefaultTypeInternal;
extern CameraSensorViewDefaultTypeInternal _CameraSensorView_default_instance_;
class GenericSensorView;
class GenericSensorViewDefaultTypeInternal;
extern GenericSensorViewDefaultTypeInternal _GenericSensorView_default_instance_;
class LidarSensorView;
class LidarSensorViewDefaultTypeInternal;
extern LidarSensorViewDefaultTypeInternal _LidarSensorView_default_instance_;
class LidarSensorView_Reflection;
class LidarSensorView_ReflectionDefaultTypeInternal;
extern LidarSensorView_ReflectionDefaultTypeInternal _LidarSensorView_Reflection_default_instance_;
class RadarSensorView;
class RadarSensorViewDefaultTypeInternal;
extern RadarSensorViewDefaultTypeInternal _RadarSensorView_default_instance_;
class RadarSensorView_Reflection;
class RadarSensorView_ReflectionDefaultTypeInternal;
extern RadarSensorView_ReflectionDefaultTypeInternal _RadarSensorView_Reflection_default_instance_;
class SensorView;
class SensorViewDefaultTypeInternal;
extern SensorViewDefaultTypeInternal _SensorView_default_instance_;
class UltrasonicSensorView;
class UltrasonicSensorViewDefaultTypeInternal;
extern UltrasonicSensorViewDefaultTypeInternal _UltrasonicSensorView_default_instance_;
}  // namespace osi3
namespace osi3 {

// ===================================================================

class SensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.SensorView) */ {
 public:
  SensorView();
  virtual ~SensorView();

  SensorView(const SensorView& from);

  inline SensorView& operator=(const SensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SensorView(SensorView&& from) noexcept
    : SensorView() {
    *this = ::std::move(from);
  }

  inline SensorView& operator=(SensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SensorView* internal_default_instance() {
    return reinterpret_cast<const SensorView*>(
               &_SensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SensorView* other);
  friend void swap(SensorView& a, SensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  SensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SensorView& from);
  void MergeFrom(const SensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .osi3.GenericSensorView generic_sensor_view = 1000;
  int generic_sensor_view_size() const;
  void clear_generic_sensor_view();
  static const int kGenericSensorViewFieldNumber = 1000;
  const ::osi3::GenericSensorView& generic_sensor_view(int index) const;
  ::osi3::GenericSensorView* mutable_generic_sensor_view(int index);
  ::osi3::GenericSensorView* add_generic_sensor_view();
  ::google::protobuf::RepeatedPtrField< ::osi3::GenericSensorView >*
      mutable_generic_sensor_view();
  const ::google::protobuf::RepeatedPtrField< ::osi3::GenericSensorView >&
      generic_sensor_view() const;

  // repeated .osi3.RadarSensorView radar_sensor_view = 1001;
  int radar_sensor_view_size() const;
  void clear_radar_sensor_view();
  static const int kRadarSensorViewFieldNumber = 1001;
  const ::osi3::RadarSensorView& radar_sensor_view(int index) const;
  ::osi3::RadarSensorView* mutable_radar_sensor_view(int index);
  ::osi3::RadarSensorView* add_radar_sensor_view();
  ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView >*
      mutable_radar_sensor_view();
  const ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView >&
      radar_sensor_view() const;

  // repeated .osi3.LidarSensorView lidar_sensor_view = 1002;
  int lidar_sensor_view_size() const;
  void clear_lidar_sensor_view();
  static const int kLidarSensorViewFieldNumber = 1002;
  const ::osi3::LidarSensorView& lidar_sensor_view(int index) const;
  ::osi3::LidarSensorView* mutable_lidar_sensor_view(int index);
  ::osi3::LidarSensorView* add_lidar_sensor_view();
  ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView >*
      mutable_lidar_sensor_view();
  const ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView >&
      lidar_sensor_view() const;

  // repeated .osi3.CameraSensorView camera_sensor_view = 1003;
  int camera_sensor_view_size() const;
  void clear_camera_sensor_view();
  static const int kCameraSensorViewFieldNumber = 1003;
  const ::osi3::CameraSensorView& camera_sensor_view(int index) const;
  ::osi3::CameraSensorView* mutable_camera_sensor_view(int index);
  ::osi3::CameraSensorView* add_camera_sensor_view();
  ::google::protobuf::RepeatedPtrField< ::osi3::CameraSensorView >*
      mutable_camera_sensor_view();
  const ::google::protobuf::RepeatedPtrField< ::osi3::CameraSensorView >&
      camera_sensor_view() const;

  // repeated .osi3.UltrasonicSensorView ultrasonic_sensor_view = 1004;
  int ultrasonic_sensor_view_size() const;
  void clear_ultrasonic_sensor_view();
  static const int kUltrasonicSensorViewFieldNumber = 1004;
  const ::osi3::UltrasonicSensorView& ultrasonic_sensor_view(int index) const;
  ::osi3::UltrasonicSensorView* mutable_ultrasonic_sensor_view(int index);
  ::osi3::UltrasonicSensorView* add_ultrasonic_sensor_view();
  ::google::protobuf::RepeatedPtrField< ::osi3::UltrasonicSensorView >*
      mutable_ultrasonic_sensor_view();
  const ::google::protobuf::RepeatedPtrField< ::osi3::UltrasonicSensorView >&
      ultrasonic_sensor_view() const;

  // .osi3.InterfaceVersion version = 1;
  bool has_version() const;
  void clear_version();
  static const int kVersionFieldNumber = 1;
  const ::osi3::InterfaceVersion& version() const;
  ::osi3::InterfaceVersion* release_version();
  ::osi3::InterfaceVersion* mutable_version();
  void set_allocated_version(::osi3::InterfaceVersion* version);

  // .osi3.Timestamp timestamp = 2;
  bool has_timestamp() const;
  void clear_timestamp();
  static const int kTimestampFieldNumber = 2;
  const ::osi3::Timestamp& timestamp() const;
  ::osi3::Timestamp* release_timestamp();
  ::osi3::Timestamp* mutable_timestamp();
  void set_allocated_timestamp(::osi3::Timestamp* timestamp);

  // .osi3.Identifier sensor_id = 3;
  bool has_sensor_id() const;
  void clear_sensor_id();
  static const int kSensorIdFieldNumber = 3;
  const ::osi3::Identifier& sensor_id() const;
  ::osi3::Identifier* release_sensor_id();
  ::osi3::Identifier* mutable_sensor_id();
  void set_allocated_sensor_id(::osi3::Identifier* sensor_id);

  // .osi3.MountingPosition mounting_position = 4;
  bool has_mounting_position() const;
  void clear_mounting_position();
  static const int kMountingPositionFieldNumber = 4;
  const ::osi3::MountingPosition& mounting_position() const;
  ::osi3::MountingPosition* release_mounting_position();
  ::osi3::MountingPosition* mutable_mounting_position();
  void set_allocated_mounting_position(::osi3::MountingPosition* mounting_position);

  // .osi3.MountingPosition mounting_position_rmse = 5;
  bool has_mounting_position_rmse() const;
  void clear_mounting_position_rmse();
  static const int kMountingPositionRmseFieldNumber = 5;
  const ::osi3::MountingPosition& mounting_position_rmse() const;
  ::osi3::MountingPosition* release_mounting_position_rmse();
  ::osi3::MountingPosition* mutable_mounting_position_rmse();
  void set_allocated_mounting_position_rmse(::osi3::MountingPosition* mounting_position_rmse);

  // .osi3.HostVehicleData host_vehicle_data = 6;
  bool has_host_vehicle_data() const;
  void clear_host_vehicle_data();
  static const int kHostVehicleDataFieldNumber = 6;
  const ::osi3::HostVehicleData& host_vehicle_data() const;
  ::osi3::HostVehicleData* release_host_vehicle_data();
  ::osi3::HostVehicleData* mutable_host_vehicle_data();
  void set_allocated_host_vehicle_data(::osi3::HostVehicleData* host_vehicle_data);

  // .osi3.GroundTruth global_ground_truth = 7;
  bool has_global_ground_truth() const;
  void clear_global_ground_truth();
  static const int kGlobalGroundTruthFieldNumber = 7;
  const ::osi3::GroundTruth& global_ground_truth() const;
  ::osi3::GroundTruth* release_global_ground_truth();
  ::osi3::GroundTruth* mutable_global_ground_truth();
  void set_allocated_global_ground_truth(::osi3::GroundTruth* global_ground_truth);

  // .osi3.Identifier host_vehicle_id = 8;
  bool has_host_vehicle_id() const;
  void clear_host_vehicle_id();
  static const int kHostVehicleIdFieldNumber = 8;
  const ::osi3::Identifier& host_vehicle_id() const;
  ::osi3::Identifier* release_host_vehicle_id();
  ::osi3::Identifier* mutable_host_vehicle_id();
  void set_allocated_host_vehicle_id(::osi3::Identifier* host_vehicle_id);

  // @@protoc_insertion_point(class_scope:osi3.SensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::osi3::GenericSensorView > generic_sensor_view_;
  ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView > radar_sensor_view_;
  ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView > lidar_sensor_view_;
  ::google::protobuf::RepeatedPtrField< ::osi3::CameraSensorView > camera_sensor_view_;
  ::google::protobuf::RepeatedPtrField< ::osi3::UltrasonicSensorView > ultrasonic_sensor_view_;
  ::osi3::InterfaceVersion* version_;
  ::osi3::Timestamp* timestamp_;
  ::osi3::Identifier* sensor_id_;
  ::osi3::MountingPosition* mounting_position_;
  ::osi3::MountingPosition* mounting_position_rmse_;
  ::osi3::HostVehicleData* host_vehicle_data_;
  ::osi3::GroundTruth* global_ground_truth_;
  ::osi3::Identifier* host_vehicle_id_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsSensorViewImpl();
};
// -------------------------------------------------------------------

class GenericSensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.GenericSensorView) */ {
 public:
  GenericSensorView();
  virtual ~GenericSensorView();

  GenericSensorView(const GenericSensorView& from);

  inline GenericSensorView& operator=(const GenericSensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  GenericSensorView(GenericSensorView&& from) noexcept
    : GenericSensorView() {
    *this = ::std::move(from);
  }

  inline GenericSensorView& operator=(GenericSensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const GenericSensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const GenericSensorView* internal_default_instance() {
    return reinterpret_cast<const GenericSensorView*>(
               &_GenericSensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(GenericSensorView* other);
  friend void swap(GenericSensorView& a, GenericSensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline GenericSensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  GenericSensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const GenericSensorView& from);
  void MergeFrom(const GenericSensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(GenericSensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .osi3.GenericSensorViewConfiguration view_configuration = 1;
  bool has_view_configuration() const;
  void clear_view_configuration();
  static const int kViewConfigurationFieldNumber = 1;
  const ::osi3::GenericSensorViewConfiguration& view_configuration() const;
  ::osi3::GenericSensorViewConfiguration* release_view_configuration();
  ::osi3::GenericSensorViewConfiguration* mutable_view_configuration();
  void set_allocated_view_configuration(::osi3::GenericSensorViewConfiguration* view_configuration);

  // @@protoc_insertion_point(class_scope:osi3.GenericSensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::osi3::GenericSensorViewConfiguration* view_configuration_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsGenericSensorViewImpl();
};
// -------------------------------------------------------------------

class RadarSensorView_Reflection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.RadarSensorView.Reflection) */ {
 public:
  RadarSensorView_Reflection();
  virtual ~RadarSensorView_Reflection();

  RadarSensorView_Reflection(const RadarSensorView_Reflection& from);

  inline RadarSensorView_Reflection& operator=(const RadarSensorView_Reflection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RadarSensorView_Reflection(RadarSensorView_Reflection&& from) noexcept
    : RadarSensorView_Reflection() {
    *this = ::std::move(from);
  }

  inline RadarSensorView_Reflection& operator=(RadarSensorView_Reflection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarSensorView_Reflection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RadarSensorView_Reflection* internal_default_instance() {
    return reinterpret_cast<const RadarSensorView_Reflection*>(
               &_RadarSensorView_Reflection_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    2;

  void Swap(RadarSensorView_Reflection* other);
  friend void swap(RadarSensorView_Reflection& a, RadarSensorView_Reflection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RadarSensorView_Reflection* New() const PROTOBUF_FINAL { return New(NULL); }

  RadarSensorView_Reflection* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RadarSensorView_Reflection& from);
  void MergeFrom(const RadarSensorView_Reflection& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RadarSensorView_Reflection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // double signal_strength = 1;
  void clear_signal_strength();
  static const int kSignalStrengthFieldNumber = 1;
  double signal_strength() const;
  void set_signal_strength(double value);

  // double time_of_flight = 2;
  void clear_time_of_flight();
  static const int kTimeOfFlightFieldNumber = 2;
  double time_of_flight() const;
  void set_time_of_flight(double value);

  // double doppler_shift = 3;
  void clear_doppler_shift();
  static const int kDopplerShiftFieldNumber = 3;
  double doppler_shift() const;
  void set_doppler_shift(double value);

  // double source_horizontal_angle = 4;
  void clear_source_horizontal_angle();
  static const int kSourceHorizontalAngleFieldNumber = 4;
  double source_horizontal_angle() const;
  void set_source_horizontal_angle(double value);

  // double source_vertical_angle = 5;
  void clear_source_vertical_angle();
  static const int kSourceVerticalAngleFieldNumber = 5;
  double source_vertical_angle() const;
  void set_source_vertical_angle(double value);

  // @@protoc_insertion_point(class_scope:osi3.RadarSensorView.Reflection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  double signal_strength_;
  double time_of_flight_;
  double doppler_shift_;
  double source_horizontal_angle_;
  double source_vertical_angle_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsRadarSensorView_ReflectionImpl();
};
// -------------------------------------------------------------------

class RadarSensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.RadarSensorView) */ {
 public:
  RadarSensorView();
  virtual ~RadarSensorView();

  RadarSensorView(const RadarSensorView& from);

  inline RadarSensorView& operator=(const RadarSensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RadarSensorView(RadarSensorView&& from) noexcept
    : RadarSensorView() {
    *this = ::std::move(from);
  }

  inline RadarSensorView& operator=(RadarSensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RadarSensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RadarSensorView* internal_default_instance() {
    return reinterpret_cast<const RadarSensorView*>(
               &_RadarSensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    3;

  void Swap(RadarSensorView* other);
  friend void swap(RadarSensorView& a, RadarSensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RadarSensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  RadarSensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RadarSensorView& from);
  void MergeFrom(const RadarSensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RadarSensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef RadarSensorView_Reflection Reflection;

  // accessors -------------------------------------------------------

  // repeated .osi3.RadarSensorView.Reflection reflection = 2;
  int reflection_size() const;
  void clear_reflection();
  static const int kReflectionFieldNumber = 2;
  const ::osi3::RadarSensorView_Reflection& reflection(int index) const;
  ::osi3::RadarSensorView_Reflection* mutable_reflection(int index);
  ::osi3::RadarSensorView_Reflection* add_reflection();
  ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView_Reflection >*
      mutable_reflection();
  const ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView_Reflection >&
      reflection() const;

  // .osi3.RadarSensorViewConfiguration view_configuration = 1;
  bool has_view_configuration() const;
  void clear_view_configuration();
  static const int kViewConfigurationFieldNumber = 1;
  const ::osi3::RadarSensorViewConfiguration& view_configuration() const;
  ::osi3::RadarSensorViewConfiguration* release_view_configuration();
  ::osi3::RadarSensorViewConfiguration* mutable_view_configuration();
  void set_allocated_view_configuration(::osi3::RadarSensorViewConfiguration* view_configuration);

  // @@protoc_insertion_point(class_scope:osi3.RadarSensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView_Reflection > reflection_;
  ::osi3::RadarSensorViewConfiguration* view_configuration_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsRadarSensorViewImpl();
};
// -------------------------------------------------------------------

class LidarSensorView_Reflection : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.LidarSensorView.Reflection) */ {
 public:
  LidarSensorView_Reflection();
  virtual ~LidarSensorView_Reflection();

  LidarSensorView_Reflection(const LidarSensorView_Reflection& from);

  inline LidarSensorView_Reflection& operator=(const LidarSensorView_Reflection& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LidarSensorView_Reflection(LidarSensorView_Reflection&& from) noexcept
    : LidarSensorView_Reflection() {
    *this = ::std::move(from);
  }

  inline LidarSensorView_Reflection& operator=(LidarSensorView_Reflection&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarSensorView_Reflection& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LidarSensorView_Reflection* internal_default_instance() {
    return reinterpret_cast<const LidarSensorView_Reflection*>(
               &_LidarSensorView_Reflection_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    4;

  void Swap(LidarSensorView_Reflection* other);
  friend void swap(LidarSensorView_Reflection& a, LidarSensorView_Reflection& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LidarSensorView_Reflection* New() const PROTOBUF_FINAL { return New(NULL); }

  LidarSensorView_Reflection* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LidarSensorView_Reflection& from);
  void MergeFrom(const LidarSensorView_Reflection& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LidarSensorView_Reflection* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .osi3.Vector3d normal_to_surface = 5;
  bool has_normal_to_surface() const;
  void clear_normal_to_surface();
  static const int kNormalToSurfaceFieldNumber = 5;
  const ::osi3::Vector3d& normal_to_surface() const;
  ::osi3::Vector3d* release_normal_to_surface();
  ::osi3::Vector3d* mutable_normal_to_surface();
  void set_allocated_normal_to_surface(::osi3::Vector3d* normal_to_surface);

  // .osi3.Identifier object_id = 6;
  bool has_object_id() const;
  void clear_object_id();
  static const int kObjectIdFieldNumber = 6;
  const ::osi3::Identifier& object_id() const;
  ::osi3::Identifier* release_object_id();
  ::osi3::Identifier* mutable_object_id();
  void set_allocated_object_id(::osi3::Identifier* object_id);

  // double signal_strength = 1;
  void clear_signal_strength();
  static const int kSignalStrengthFieldNumber = 1;
  double signal_strength() const;
  void set_signal_strength(double value);

  // double time_of_flight = 2;
  void clear_time_of_flight();
  static const int kTimeOfFlightFieldNumber = 2;
  double time_of_flight() const;
  void set_time_of_flight(double value);

  // double doppler_shift = 3;
  void clear_doppler_shift();
  static const int kDopplerShiftFieldNumber = 3;
  double doppler_shift() const;
  void set_doppler_shift(double value);

  // @@protoc_insertion_point(class_scope:osi3.LidarSensorView.Reflection)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::osi3::Vector3d* normal_to_surface_;
  ::osi3::Identifier* object_id_;
  double signal_strength_;
  double time_of_flight_;
  double doppler_shift_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsLidarSensorView_ReflectionImpl();
};
// -------------------------------------------------------------------

class LidarSensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.LidarSensorView) */ {
 public:
  LidarSensorView();
  virtual ~LidarSensorView();

  LidarSensorView(const LidarSensorView& from);

  inline LidarSensorView& operator=(const LidarSensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  LidarSensorView(LidarSensorView&& from) noexcept
    : LidarSensorView() {
    *this = ::std::move(from);
  }

  inline LidarSensorView& operator=(LidarSensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const LidarSensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const LidarSensorView* internal_default_instance() {
    return reinterpret_cast<const LidarSensorView*>(
               &_LidarSensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    5;

  void Swap(LidarSensorView* other);
  friend void swap(LidarSensorView& a, LidarSensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline LidarSensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  LidarSensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const LidarSensorView& from);
  void MergeFrom(const LidarSensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(LidarSensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef LidarSensorView_Reflection Reflection;

  // accessors -------------------------------------------------------

  // repeated .osi3.LidarSensorView.Reflection reflection = 2;
  int reflection_size() const;
  void clear_reflection();
  static const int kReflectionFieldNumber = 2;
  const ::osi3::LidarSensorView_Reflection& reflection(int index) const;
  ::osi3::LidarSensorView_Reflection* mutable_reflection(int index);
  ::osi3::LidarSensorView_Reflection* add_reflection();
  ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView_Reflection >*
      mutable_reflection();
  const ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView_Reflection >&
      reflection() const;

  // .osi3.LidarSensorViewConfiguration view_configuration = 1;
  bool has_view_configuration() const;
  void clear_view_configuration();
  static const int kViewConfigurationFieldNumber = 1;
  const ::osi3::LidarSensorViewConfiguration& view_configuration() const;
  ::osi3::LidarSensorViewConfiguration* release_view_configuration();
  ::osi3::LidarSensorViewConfiguration* mutable_view_configuration();
  void set_allocated_view_configuration(::osi3::LidarSensorViewConfiguration* view_configuration);

  // @@protoc_insertion_point(class_scope:osi3.LidarSensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView_Reflection > reflection_;
  ::osi3::LidarSensorViewConfiguration* view_configuration_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsLidarSensorViewImpl();
};
// -------------------------------------------------------------------

class CameraSensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.CameraSensorView) */ {
 public:
  CameraSensorView();
  virtual ~CameraSensorView();

  CameraSensorView(const CameraSensorView& from);

  inline CameraSensorView& operator=(const CameraSensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  CameraSensorView(CameraSensorView&& from) noexcept
    : CameraSensorView() {
    *this = ::std::move(from);
  }

  inline CameraSensorView& operator=(CameraSensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const CameraSensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const CameraSensorView* internal_default_instance() {
    return reinterpret_cast<const CameraSensorView*>(
               &_CameraSensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    6;

  void Swap(CameraSensorView* other);
  friend void swap(CameraSensorView& a, CameraSensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline CameraSensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  CameraSensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const CameraSensorView& from);
  void MergeFrom(const CameraSensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(CameraSensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // bytes image_data = 2;
  void clear_image_data();
  static const int kImageDataFieldNumber = 2;
  const ::std::string& image_data() const;
  void set_image_data(const ::std::string& value);
  #if LANG_CXX11
  void set_image_data(::std::string&& value);
  #endif
  void set_image_data(const char* value);
  void set_image_data(const void* value, size_t size);
  ::std::string* mutable_image_data();
  ::std::string* release_image_data();
  void set_allocated_image_data(::std::string* image_data);

  // .osi3.CameraSensorViewConfiguration view_configuration = 1;
  bool has_view_configuration() const;
  void clear_view_configuration();
  static const int kViewConfigurationFieldNumber = 1;
  const ::osi3::CameraSensorViewConfiguration& view_configuration() const;
  ::osi3::CameraSensorViewConfiguration* release_view_configuration();
  ::osi3::CameraSensorViewConfiguration* mutable_view_configuration();
  void set_allocated_view_configuration(::osi3::CameraSensorViewConfiguration* view_configuration);

  // @@protoc_insertion_point(class_scope:osi3.CameraSensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr image_data_;
  ::osi3::CameraSensorViewConfiguration* view_configuration_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsCameraSensorViewImpl();
};
// -------------------------------------------------------------------

class UltrasonicSensorView : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.UltrasonicSensorView) */ {
 public:
  UltrasonicSensorView();
  virtual ~UltrasonicSensorView();

  UltrasonicSensorView(const UltrasonicSensorView& from);

  inline UltrasonicSensorView& operator=(const UltrasonicSensorView& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  UltrasonicSensorView(UltrasonicSensorView&& from) noexcept
    : UltrasonicSensorView() {
    *this = ::std::move(from);
  }

  inline UltrasonicSensorView& operator=(UltrasonicSensorView&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const UltrasonicSensorView& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const UltrasonicSensorView* internal_default_instance() {
    return reinterpret_cast<const UltrasonicSensorView*>(
               &_UltrasonicSensorView_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    7;

  void Swap(UltrasonicSensorView* other);
  friend void swap(UltrasonicSensorView& a, UltrasonicSensorView& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline UltrasonicSensorView* New() const PROTOBUF_FINAL { return New(NULL); }

  UltrasonicSensorView* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const UltrasonicSensorView& from);
  void MergeFrom(const UltrasonicSensorView& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(UltrasonicSensorView* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // .osi3.UltrasonicSensorViewConfiguration view_configuration = 1;
  bool has_view_configuration() const;
  void clear_view_configuration();
  static const int kViewConfigurationFieldNumber = 1;
  const ::osi3::UltrasonicSensorViewConfiguration& view_configuration() const;
  ::osi3::UltrasonicSensorViewConfiguration* release_view_configuration();
  ::osi3::UltrasonicSensorViewConfiguration* mutable_view_configuration();
  void set_allocated_view_configuration(::osi3::UltrasonicSensorViewConfiguration* view_configuration);

  // @@protoc_insertion_point(class_scope:osi3.UltrasonicSensorView)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::osi3::UltrasonicSensorViewConfiguration* view_configuration_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5fsensorview_2eproto::TableStruct;
  friend void ::protobuf_osi_5fsensorview_2eproto::InitDefaultsUltrasonicSensorViewImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SensorView

// .osi3.InterfaceVersion version = 1;
inline bool SensorView::has_version() const {
  return this != internal_default_instance() && version_ != NULL;
}
inline const ::osi3::InterfaceVersion& SensorView::version() const {
  const ::osi3::InterfaceVersion* p = version_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.version)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::InterfaceVersion*>(
      &::osi3::_InterfaceVersion_default_instance_);
}
inline ::osi3::InterfaceVersion* SensorView::release_version() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.version)
  
  ::osi3::InterfaceVersion* temp = version_;
  version_ = NULL;
  return temp;
}
inline ::osi3::InterfaceVersion* SensorView::mutable_version() {
  
  if (version_ == NULL) {
    version_ = new ::osi3::InterfaceVersion;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.version)
  return version_;
}
inline void SensorView::set_allocated_version(::osi3::InterfaceVersion* version) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(version_);
  }
  if (version) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      version = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, version, submessage_arena);
    }
    
  } else {
    
  }
  version_ = version;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.version)
}

// .osi3.Timestamp timestamp = 2;
inline bool SensorView::has_timestamp() const {
  return this != internal_default_instance() && timestamp_ != NULL;
}
inline const ::osi3::Timestamp& SensorView::timestamp() const {
  const ::osi3::Timestamp* p = timestamp_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.timestamp)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Timestamp*>(
      &::osi3::_Timestamp_default_instance_);
}
inline ::osi3::Timestamp* SensorView::release_timestamp() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.timestamp)
  
  ::osi3::Timestamp* temp = timestamp_;
  timestamp_ = NULL;
  return temp;
}
inline ::osi3::Timestamp* SensorView::mutable_timestamp() {
  
  if (timestamp_ == NULL) {
    timestamp_ = new ::osi3::Timestamp;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.timestamp)
  return timestamp_;
}
inline void SensorView::set_allocated_timestamp(::osi3::Timestamp* timestamp) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(timestamp_);
  }
  if (timestamp) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      timestamp = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, timestamp, submessage_arena);
    }
    
  } else {
    
  }
  timestamp_ = timestamp;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.timestamp)
}

// .osi3.Identifier sensor_id = 3;
inline bool SensorView::has_sensor_id() const {
  return this != internal_default_instance() && sensor_id_ != NULL;
}
inline const ::osi3::Identifier& SensorView::sensor_id() const {
  const ::osi3::Identifier* p = sensor_id_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.sensor_id)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* SensorView::release_sensor_id() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.sensor_id)
  
  ::osi3::Identifier* temp = sensor_id_;
  sensor_id_ = NULL;
  return temp;
}
inline ::osi3::Identifier* SensorView::mutable_sensor_id() {
  
  if (sensor_id_ == NULL) {
    sensor_id_ = new ::osi3::Identifier;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.sensor_id)
  return sensor_id_;
}
inline void SensorView::set_allocated_sensor_id(::osi3::Identifier* sensor_id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(sensor_id_);
  }
  if (sensor_id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      sensor_id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, sensor_id, submessage_arena);
    }
    
  } else {
    
  }
  sensor_id_ = sensor_id;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.sensor_id)
}

// .osi3.MountingPosition mounting_position = 4;
inline bool SensorView::has_mounting_position() const {
  return this != internal_default_instance() && mounting_position_ != NULL;
}
inline const ::osi3::MountingPosition& SensorView::mounting_position() const {
  const ::osi3::MountingPosition* p = mounting_position_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.mounting_position)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::MountingPosition*>(
      &::osi3::_MountingPosition_default_instance_);
}
inline ::osi3::MountingPosition* SensorView::release_mounting_position() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.mounting_position)
  
  ::osi3::MountingPosition* temp = mounting_position_;
  mounting_position_ = NULL;
  return temp;
}
inline ::osi3::MountingPosition* SensorView::mutable_mounting_position() {
  
  if (mounting_position_ == NULL) {
    mounting_position_ = new ::osi3::MountingPosition;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.mounting_position)
  return mounting_position_;
}
inline void SensorView::set_allocated_mounting_position(::osi3::MountingPosition* mounting_position) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(mounting_position_);
  }
  if (mounting_position) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      mounting_position = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, mounting_position, submessage_arena);
    }
    
  } else {
    
  }
  mounting_position_ = mounting_position;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.mounting_position)
}

// .osi3.MountingPosition mounting_position_rmse = 5;
inline bool SensorView::has_mounting_position_rmse() const {
  return this != internal_default_instance() && mounting_position_rmse_ != NULL;
}
inline const ::osi3::MountingPosition& SensorView::mounting_position_rmse() const {
  const ::osi3::MountingPosition* p = mounting_position_rmse_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.mounting_position_rmse)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::MountingPosition*>(
      &::osi3::_MountingPosition_default_instance_);
}
inline ::osi3::MountingPosition* SensorView::release_mounting_position_rmse() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.mounting_position_rmse)
  
  ::osi3::MountingPosition* temp = mounting_position_rmse_;
  mounting_position_rmse_ = NULL;
  return temp;
}
inline ::osi3::MountingPosition* SensorView::mutable_mounting_position_rmse() {
  
  if (mounting_position_rmse_ == NULL) {
    mounting_position_rmse_ = new ::osi3::MountingPosition;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.mounting_position_rmse)
  return mounting_position_rmse_;
}
inline void SensorView::set_allocated_mounting_position_rmse(::osi3::MountingPosition* mounting_position_rmse) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(mounting_position_rmse_);
  }
  if (mounting_position_rmse) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      mounting_position_rmse = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, mounting_position_rmse, submessage_arena);
    }
    
  } else {
    
  }
  mounting_position_rmse_ = mounting_position_rmse;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.mounting_position_rmse)
}

// .osi3.HostVehicleData host_vehicle_data = 6;
inline bool SensorView::has_host_vehicle_data() const {
  return this != internal_default_instance() && host_vehicle_data_ != NULL;
}
inline const ::osi3::HostVehicleData& SensorView::host_vehicle_data() const {
  const ::osi3::HostVehicleData* p = host_vehicle_data_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.host_vehicle_data)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::HostVehicleData*>(
      &::osi3::_HostVehicleData_default_instance_);
}
inline ::osi3::HostVehicleData* SensorView::release_host_vehicle_data() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.host_vehicle_data)
  
  ::osi3::HostVehicleData* temp = host_vehicle_data_;
  host_vehicle_data_ = NULL;
  return temp;
}
inline ::osi3::HostVehicleData* SensorView::mutable_host_vehicle_data() {
  
  if (host_vehicle_data_ == NULL) {
    host_vehicle_data_ = new ::osi3::HostVehicleData;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.host_vehicle_data)
  return host_vehicle_data_;
}
inline void SensorView::set_allocated_host_vehicle_data(::osi3::HostVehicleData* host_vehicle_data) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(host_vehicle_data_);
  }
  if (host_vehicle_data) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      host_vehicle_data = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, host_vehicle_data, submessage_arena);
    }
    
  } else {
    
  }
  host_vehicle_data_ = host_vehicle_data;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.host_vehicle_data)
}

// .osi3.GroundTruth global_ground_truth = 7;
inline bool SensorView::has_global_ground_truth() const {
  return this != internal_default_instance() && global_ground_truth_ != NULL;
}
inline const ::osi3::GroundTruth& SensorView::global_ground_truth() const {
  const ::osi3::GroundTruth* p = global_ground_truth_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.global_ground_truth)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::GroundTruth*>(
      &::osi3::_GroundTruth_default_instance_);
}
inline ::osi3::GroundTruth* SensorView::release_global_ground_truth() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.global_ground_truth)
  
  ::osi3::GroundTruth* temp = global_ground_truth_;
  global_ground_truth_ = NULL;
  return temp;
}
inline ::osi3::GroundTruth* SensorView::mutable_global_ground_truth() {
  
  if (global_ground_truth_ == NULL) {
    global_ground_truth_ = new ::osi3::GroundTruth;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.global_ground_truth)
  return global_ground_truth_;
}
inline void SensorView::set_allocated_global_ground_truth(::osi3::GroundTruth* global_ground_truth) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(global_ground_truth_);
  }
  if (global_ground_truth) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      global_ground_truth = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, global_ground_truth, submessage_arena);
    }
    
  } else {
    
  }
  global_ground_truth_ = global_ground_truth;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.global_ground_truth)
}

// .osi3.Identifier host_vehicle_id = 8;
inline bool SensorView::has_host_vehicle_id() const {
  return this != internal_default_instance() && host_vehicle_id_ != NULL;
}
inline const ::osi3::Identifier& SensorView::host_vehicle_id() const {
  const ::osi3::Identifier* p = host_vehicle_id_;
  // @@protoc_insertion_point(field_get:osi3.SensorView.host_vehicle_id)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* SensorView::release_host_vehicle_id() {
  // @@protoc_insertion_point(field_release:osi3.SensorView.host_vehicle_id)
  
  ::osi3::Identifier* temp = host_vehicle_id_;
  host_vehicle_id_ = NULL;
  return temp;
}
inline ::osi3::Identifier* SensorView::mutable_host_vehicle_id() {
  
  if (host_vehicle_id_ == NULL) {
    host_vehicle_id_ = new ::osi3::Identifier;
  }
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.host_vehicle_id)
  return host_vehicle_id_;
}
inline void SensorView::set_allocated_host_vehicle_id(::osi3::Identifier* host_vehicle_id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(host_vehicle_id_);
  }
  if (host_vehicle_id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      host_vehicle_id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, host_vehicle_id, submessage_arena);
    }
    
  } else {
    
  }
  host_vehicle_id_ = host_vehicle_id;
  // @@protoc_insertion_point(field_set_allocated:osi3.SensorView.host_vehicle_id)
}

// repeated .osi3.GenericSensorView generic_sensor_view = 1000;
inline int SensorView::generic_sensor_view_size() const {
  return generic_sensor_view_.size();
}
inline void SensorView::clear_generic_sensor_view() {
  generic_sensor_view_.Clear();
}
inline const ::osi3::GenericSensorView& SensorView::generic_sensor_view(int index) const {
  // @@protoc_insertion_point(field_get:osi3.SensorView.generic_sensor_view)
  return generic_sensor_view_.Get(index);
}
inline ::osi3::GenericSensorView* SensorView::mutable_generic_sensor_view(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.generic_sensor_view)
  return generic_sensor_view_.Mutable(index);
}
inline ::osi3::GenericSensorView* SensorView::add_generic_sensor_view() {
  // @@protoc_insertion_point(field_add:osi3.SensorView.generic_sensor_view)
  return generic_sensor_view_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::GenericSensorView >*
SensorView::mutable_generic_sensor_view() {
  // @@protoc_insertion_point(field_mutable_list:osi3.SensorView.generic_sensor_view)
  return &generic_sensor_view_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::GenericSensorView >&
SensorView::generic_sensor_view() const {
  // @@protoc_insertion_point(field_list:osi3.SensorView.generic_sensor_view)
  return generic_sensor_view_;
}

// repeated .osi3.RadarSensorView radar_sensor_view = 1001;
inline int SensorView::radar_sensor_view_size() const {
  return radar_sensor_view_.size();
}
inline void SensorView::clear_radar_sensor_view() {
  radar_sensor_view_.Clear();
}
inline const ::osi3::RadarSensorView& SensorView::radar_sensor_view(int index) const {
  // @@protoc_insertion_point(field_get:osi3.SensorView.radar_sensor_view)
  return radar_sensor_view_.Get(index);
}
inline ::osi3::RadarSensorView* SensorView::mutable_radar_sensor_view(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.radar_sensor_view)
  return radar_sensor_view_.Mutable(index);
}
inline ::osi3::RadarSensorView* SensorView::add_radar_sensor_view() {
  // @@protoc_insertion_point(field_add:osi3.SensorView.radar_sensor_view)
  return radar_sensor_view_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView >*
SensorView::mutable_radar_sensor_view() {
  // @@protoc_insertion_point(field_mutable_list:osi3.SensorView.radar_sensor_view)
  return &radar_sensor_view_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView >&
SensorView::radar_sensor_view() const {
  // @@protoc_insertion_point(field_list:osi3.SensorView.radar_sensor_view)
  return radar_sensor_view_;
}

// repeated .osi3.LidarSensorView lidar_sensor_view = 1002;
inline int SensorView::lidar_sensor_view_size() const {
  return lidar_sensor_view_.size();
}
inline void SensorView::clear_lidar_sensor_view() {
  lidar_sensor_view_.Clear();
}
inline const ::osi3::LidarSensorView& SensorView::lidar_sensor_view(int index) const {
  // @@protoc_insertion_point(field_get:osi3.SensorView.lidar_sensor_view)
  return lidar_sensor_view_.Get(index);
}
inline ::osi3::LidarSensorView* SensorView::mutable_lidar_sensor_view(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.lidar_sensor_view)
  return lidar_sensor_view_.Mutable(index);
}
inline ::osi3::LidarSensorView* SensorView::add_lidar_sensor_view() {
  // @@protoc_insertion_point(field_add:osi3.SensorView.lidar_sensor_view)
  return lidar_sensor_view_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView >*
SensorView::mutable_lidar_sensor_view() {
  // @@protoc_insertion_point(field_mutable_list:osi3.SensorView.lidar_sensor_view)
  return &lidar_sensor_view_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView >&
SensorView::lidar_sensor_view() const {
  // @@protoc_insertion_point(field_list:osi3.SensorView.lidar_sensor_view)
  return lidar_sensor_view_;
}

// repeated .osi3.CameraSensorView camera_sensor_view = 1003;
inline int SensorView::camera_sensor_view_size() const {
  return camera_sensor_view_.size();
}
inline void SensorView::clear_camera_sensor_view() {
  camera_sensor_view_.Clear();
}
inline const ::osi3::CameraSensorView& SensorView::camera_sensor_view(int index) const {
  // @@protoc_insertion_point(field_get:osi3.SensorView.camera_sensor_view)
  return camera_sensor_view_.Get(index);
}
inline ::osi3::CameraSensorView* SensorView::mutable_camera_sensor_view(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.camera_sensor_view)
  return camera_sensor_view_.Mutable(index);
}
inline ::osi3::CameraSensorView* SensorView::add_camera_sensor_view() {
  // @@protoc_insertion_point(field_add:osi3.SensorView.camera_sensor_view)
  return camera_sensor_view_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::CameraSensorView >*
SensorView::mutable_camera_sensor_view() {
  // @@protoc_insertion_point(field_mutable_list:osi3.SensorView.camera_sensor_view)
  return &camera_sensor_view_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::CameraSensorView >&
SensorView::camera_sensor_view() const {
  // @@protoc_insertion_point(field_list:osi3.SensorView.camera_sensor_view)
  return camera_sensor_view_;
}

// repeated .osi3.UltrasonicSensorView ultrasonic_sensor_view = 1004;
inline int SensorView::ultrasonic_sensor_view_size() const {
  return ultrasonic_sensor_view_.size();
}
inline void SensorView::clear_ultrasonic_sensor_view() {
  ultrasonic_sensor_view_.Clear();
}
inline const ::osi3::UltrasonicSensorView& SensorView::ultrasonic_sensor_view(int index) const {
  // @@protoc_insertion_point(field_get:osi3.SensorView.ultrasonic_sensor_view)
  return ultrasonic_sensor_view_.Get(index);
}
inline ::osi3::UltrasonicSensorView* SensorView::mutable_ultrasonic_sensor_view(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.SensorView.ultrasonic_sensor_view)
  return ultrasonic_sensor_view_.Mutable(index);
}
inline ::osi3::UltrasonicSensorView* SensorView::add_ultrasonic_sensor_view() {
  // @@protoc_insertion_point(field_add:osi3.SensorView.ultrasonic_sensor_view)
  return ultrasonic_sensor_view_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::UltrasonicSensorView >*
SensorView::mutable_ultrasonic_sensor_view() {
  // @@protoc_insertion_point(field_mutable_list:osi3.SensorView.ultrasonic_sensor_view)
  return &ultrasonic_sensor_view_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::UltrasonicSensorView >&
SensorView::ultrasonic_sensor_view() const {
  // @@protoc_insertion_point(field_list:osi3.SensorView.ultrasonic_sensor_view)
  return ultrasonic_sensor_view_;
}

// -------------------------------------------------------------------

// GenericSensorView

// .osi3.GenericSensorViewConfiguration view_configuration = 1;
inline bool GenericSensorView::has_view_configuration() const {
  return this != internal_default_instance() && view_configuration_ != NULL;
}
inline const ::osi3::GenericSensorViewConfiguration& GenericSensorView::view_configuration() const {
  const ::osi3::GenericSensorViewConfiguration* p = view_configuration_;
  // @@protoc_insertion_point(field_get:osi3.GenericSensorView.view_configuration)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::GenericSensorViewConfiguration*>(
      &::osi3::_GenericSensorViewConfiguration_default_instance_);
}
inline ::osi3::GenericSensorViewConfiguration* GenericSensorView::release_view_configuration() {
  // @@protoc_insertion_point(field_release:osi3.GenericSensorView.view_configuration)
  
  ::osi3::GenericSensorViewConfiguration* temp = view_configuration_;
  view_configuration_ = NULL;
  return temp;
}
inline ::osi3::GenericSensorViewConfiguration* GenericSensorView::mutable_view_configuration() {
  
  if (view_configuration_ == NULL) {
    view_configuration_ = new ::osi3::GenericSensorViewConfiguration;
  }
  // @@protoc_insertion_point(field_mutable:osi3.GenericSensorView.view_configuration)
  return view_configuration_;
}
inline void GenericSensorView::set_allocated_view_configuration(::osi3::GenericSensorViewConfiguration* view_configuration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_configuration_);
  }
  if (view_configuration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      view_configuration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_configuration, submessage_arena);
    }
    
  } else {
    
  }
  view_configuration_ = view_configuration;
  // @@protoc_insertion_point(field_set_allocated:osi3.GenericSensorView.view_configuration)
}

// -------------------------------------------------------------------

// RadarSensorView_Reflection

// double signal_strength = 1;
inline void RadarSensorView_Reflection::clear_signal_strength() {
  signal_strength_ = 0;
}
inline double RadarSensorView_Reflection::signal_strength() const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.Reflection.signal_strength)
  return signal_strength_;
}
inline void RadarSensorView_Reflection::set_signal_strength(double value) {
  
  signal_strength_ = value;
  // @@protoc_insertion_point(field_set:osi3.RadarSensorView.Reflection.signal_strength)
}

// double time_of_flight = 2;
inline void RadarSensorView_Reflection::clear_time_of_flight() {
  time_of_flight_ = 0;
}
inline double RadarSensorView_Reflection::time_of_flight() const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.Reflection.time_of_flight)
  return time_of_flight_;
}
inline void RadarSensorView_Reflection::set_time_of_flight(double value) {
  
  time_of_flight_ = value;
  // @@protoc_insertion_point(field_set:osi3.RadarSensorView.Reflection.time_of_flight)
}

// double doppler_shift = 3;
inline void RadarSensorView_Reflection::clear_doppler_shift() {
  doppler_shift_ = 0;
}
inline double RadarSensorView_Reflection::doppler_shift() const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.Reflection.doppler_shift)
  return doppler_shift_;
}
inline void RadarSensorView_Reflection::set_doppler_shift(double value) {
  
  doppler_shift_ = value;
  // @@protoc_insertion_point(field_set:osi3.RadarSensorView.Reflection.doppler_shift)
}

// double source_horizontal_angle = 4;
inline void RadarSensorView_Reflection::clear_source_horizontal_angle() {
  source_horizontal_angle_ = 0;
}
inline double RadarSensorView_Reflection::source_horizontal_angle() const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.Reflection.source_horizontal_angle)
  return source_horizontal_angle_;
}
inline void RadarSensorView_Reflection::set_source_horizontal_angle(double value) {
  
  source_horizontal_angle_ = value;
  // @@protoc_insertion_point(field_set:osi3.RadarSensorView.Reflection.source_horizontal_angle)
}

// double source_vertical_angle = 5;
inline void RadarSensorView_Reflection::clear_source_vertical_angle() {
  source_vertical_angle_ = 0;
}
inline double RadarSensorView_Reflection::source_vertical_angle() const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.Reflection.source_vertical_angle)
  return source_vertical_angle_;
}
inline void RadarSensorView_Reflection::set_source_vertical_angle(double value) {
  
  source_vertical_angle_ = value;
  // @@protoc_insertion_point(field_set:osi3.RadarSensorView.Reflection.source_vertical_angle)
}

// -------------------------------------------------------------------

// RadarSensorView

// .osi3.RadarSensorViewConfiguration view_configuration = 1;
inline bool RadarSensorView::has_view_configuration() const {
  return this != internal_default_instance() && view_configuration_ != NULL;
}
inline const ::osi3::RadarSensorViewConfiguration& RadarSensorView::view_configuration() const {
  const ::osi3::RadarSensorViewConfiguration* p = view_configuration_;
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.view_configuration)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::RadarSensorViewConfiguration*>(
      &::osi3::_RadarSensorViewConfiguration_default_instance_);
}
inline ::osi3::RadarSensorViewConfiguration* RadarSensorView::release_view_configuration() {
  // @@protoc_insertion_point(field_release:osi3.RadarSensorView.view_configuration)
  
  ::osi3::RadarSensorViewConfiguration* temp = view_configuration_;
  view_configuration_ = NULL;
  return temp;
}
inline ::osi3::RadarSensorViewConfiguration* RadarSensorView::mutable_view_configuration() {
  
  if (view_configuration_ == NULL) {
    view_configuration_ = new ::osi3::RadarSensorViewConfiguration;
  }
  // @@protoc_insertion_point(field_mutable:osi3.RadarSensorView.view_configuration)
  return view_configuration_;
}
inline void RadarSensorView::set_allocated_view_configuration(::osi3::RadarSensorViewConfiguration* view_configuration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_configuration_);
  }
  if (view_configuration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      view_configuration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_configuration, submessage_arena);
    }
    
  } else {
    
  }
  view_configuration_ = view_configuration;
  // @@protoc_insertion_point(field_set_allocated:osi3.RadarSensorView.view_configuration)
}

// repeated .osi3.RadarSensorView.Reflection reflection = 2;
inline int RadarSensorView::reflection_size() const {
  return reflection_.size();
}
inline void RadarSensorView::clear_reflection() {
  reflection_.Clear();
}
inline const ::osi3::RadarSensorView_Reflection& RadarSensorView::reflection(int index) const {
  // @@protoc_insertion_point(field_get:osi3.RadarSensorView.reflection)
  return reflection_.Get(index);
}
inline ::osi3::RadarSensorView_Reflection* RadarSensorView::mutable_reflection(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.RadarSensorView.reflection)
  return reflection_.Mutable(index);
}
inline ::osi3::RadarSensorView_Reflection* RadarSensorView::add_reflection() {
  // @@protoc_insertion_point(field_add:osi3.RadarSensorView.reflection)
  return reflection_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView_Reflection >*
RadarSensorView::mutable_reflection() {
  // @@protoc_insertion_point(field_mutable_list:osi3.RadarSensorView.reflection)
  return &reflection_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::RadarSensorView_Reflection >&
RadarSensorView::reflection() const {
  // @@protoc_insertion_point(field_list:osi3.RadarSensorView.reflection)
  return reflection_;
}

// -------------------------------------------------------------------

// LidarSensorView_Reflection

// double signal_strength = 1;
inline void LidarSensorView_Reflection::clear_signal_strength() {
  signal_strength_ = 0;
}
inline double LidarSensorView_Reflection::signal_strength() const {
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.Reflection.signal_strength)
  return signal_strength_;
}
inline void LidarSensorView_Reflection::set_signal_strength(double value) {
  
  signal_strength_ = value;
  // @@protoc_insertion_point(field_set:osi3.LidarSensorView.Reflection.signal_strength)
}

// double time_of_flight = 2;
inline void LidarSensorView_Reflection::clear_time_of_flight() {
  time_of_flight_ = 0;
}
inline double LidarSensorView_Reflection::time_of_flight() const {
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.Reflection.time_of_flight)
  return time_of_flight_;
}
inline void LidarSensorView_Reflection::set_time_of_flight(double value) {
  
  time_of_flight_ = value;
  // @@protoc_insertion_point(field_set:osi3.LidarSensorView.Reflection.time_of_flight)
}

// double doppler_shift = 3;
inline void LidarSensorView_Reflection::clear_doppler_shift() {
  doppler_shift_ = 0;
}
inline double LidarSensorView_Reflection::doppler_shift() const {
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.Reflection.doppler_shift)
  return doppler_shift_;
}
inline void LidarSensorView_Reflection::set_doppler_shift(double value) {
  
  doppler_shift_ = value;
  // @@protoc_insertion_point(field_set:osi3.LidarSensorView.Reflection.doppler_shift)
}

// .osi3.Vector3d normal_to_surface = 5;
inline bool LidarSensorView_Reflection::has_normal_to_surface() const {
  return this != internal_default_instance() && normal_to_surface_ != NULL;
}
inline const ::osi3::Vector3d& LidarSensorView_Reflection::normal_to_surface() const {
  const ::osi3::Vector3d* p = normal_to_surface_;
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.Reflection.normal_to_surface)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Vector3d*>(
      &::osi3::_Vector3d_default_instance_);
}
inline ::osi3::Vector3d* LidarSensorView_Reflection::release_normal_to_surface() {
  // @@protoc_insertion_point(field_release:osi3.LidarSensorView.Reflection.normal_to_surface)
  
  ::osi3::Vector3d* temp = normal_to_surface_;
  normal_to_surface_ = NULL;
  return temp;
}
inline ::osi3::Vector3d* LidarSensorView_Reflection::mutable_normal_to_surface() {
  
  if (normal_to_surface_ == NULL) {
    normal_to_surface_ = new ::osi3::Vector3d;
  }
  // @@protoc_insertion_point(field_mutable:osi3.LidarSensorView.Reflection.normal_to_surface)
  return normal_to_surface_;
}
inline void LidarSensorView_Reflection::set_allocated_normal_to_surface(::osi3::Vector3d* normal_to_surface) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(normal_to_surface_);
  }
  if (normal_to_surface) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      normal_to_surface = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, normal_to_surface, submessage_arena);
    }
    
  } else {
    
  }
  normal_to_surface_ = normal_to_surface;
  // @@protoc_insertion_point(field_set_allocated:osi3.LidarSensorView.Reflection.normal_to_surface)
}

// .osi3.Identifier object_id = 6;
inline bool LidarSensorView_Reflection::has_object_id() const {
  return this != internal_default_instance() && object_id_ != NULL;
}
inline const ::osi3::Identifier& LidarSensorView_Reflection::object_id() const {
  const ::osi3::Identifier* p = object_id_;
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.Reflection.object_id)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* LidarSensorView_Reflection::release_object_id() {
  // @@protoc_insertion_point(field_release:osi3.LidarSensorView.Reflection.object_id)
  
  ::osi3::Identifier* temp = object_id_;
  object_id_ = NULL;
  return temp;
}
inline ::osi3::Identifier* LidarSensorView_Reflection::mutable_object_id() {
  
  if (object_id_ == NULL) {
    object_id_ = new ::osi3::Identifier;
  }
  // @@protoc_insertion_point(field_mutable:osi3.LidarSensorView.Reflection.object_id)
  return object_id_;
}
inline void LidarSensorView_Reflection::set_allocated_object_id(::osi3::Identifier* object_id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(object_id_);
  }
  if (object_id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      object_id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, object_id, submessage_arena);
    }
    
  } else {
    
  }
  object_id_ = object_id;
  // @@protoc_insertion_point(field_set_allocated:osi3.LidarSensorView.Reflection.object_id)
}

// -------------------------------------------------------------------

// LidarSensorView

// .osi3.LidarSensorViewConfiguration view_configuration = 1;
inline bool LidarSensorView::has_view_configuration() const {
  return this != internal_default_instance() && view_configuration_ != NULL;
}
inline const ::osi3::LidarSensorViewConfiguration& LidarSensorView::view_configuration() const {
  const ::osi3::LidarSensorViewConfiguration* p = view_configuration_;
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.view_configuration)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::LidarSensorViewConfiguration*>(
      &::osi3::_LidarSensorViewConfiguration_default_instance_);
}
inline ::osi3::LidarSensorViewConfiguration* LidarSensorView::release_view_configuration() {
  // @@protoc_insertion_point(field_release:osi3.LidarSensorView.view_configuration)
  
  ::osi3::LidarSensorViewConfiguration* temp = view_configuration_;
  view_configuration_ = NULL;
  return temp;
}
inline ::osi3::LidarSensorViewConfiguration* LidarSensorView::mutable_view_configuration() {
  
  if (view_configuration_ == NULL) {
    view_configuration_ = new ::osi3::LidarSensorViewConfiguration;
  }
  // @@protoc_insertion_point(field_mutable:osi3.LidarSensorView.view_configuration)
  return view_configuration_;
}
inline void LidarSensorView::set_allocated_view_configuration(::osi3::LidarSensorViewConfiguration* view_configuration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_configuration_);
  }
  if (view_configuration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      view_configuration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_configuration, submessage_arena);
    }
    
  } else {
    
  }
  view_configuration_ = view_configuration;
  // @@protoc_insertion_point(field_set_allocated:osi3.LidarSensorView.view_configuration)
}

// repeated .osi3.LidarSensorView.Reflection reflection = 2;
inline int LidarSensorView::reflection_size() const {
  return reflection_.size();
}
inline void LidarSensorView::clear_reflection() {
  reflection_.Clear();
}
inline const ::osi3::LidarSensorView_Reflection& LidarSensorView::reflection(int index) const {
  // @@protoc_insertion_point(field_get:osi3.LidarSensorView.reflection)
  return reflection_.Get(index);
}
inline ::osi3::LidarSensorView_Reflection* LidarSensorView::mutable_reflection(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.LidarSensorView.reflection)
  return reflection_.Mutable(index);
}
inline ::osi3::LidarSensorView_Reflection* LidarSensorView::add_reflection() {
  // @@protoc_insertion_point(field_add:osi3.LidarSensorView.reflection)
  return reflection_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView_Reflection >*
LidarSensorView::mutable_reflection() {
  // @@protoc_insertion_point(field_mutable_list:osi3.LidarSensorView.reflection)
  return &reflection_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::LidarSensorView_Reflection >&
LidarSensorView::reflection() const {
  // @@protoc_insertion_point(field_list:osi3.LidarSensorView.reflection)
  return reflection_;
}

// -------------------------------------------------------------------

// CameraSensorView

// .osi3.CameraSensorViewConfiguration view_configuration = 1;
inline bool CameraSensorView::has_view_configuration() const {
  return this != internal_default_instance() && view_configuration_ != NULL;
}
inline const ::osi3::CameraSensorViewConfiguration& CameraSensorView::view_configuration() const {
  const ::osi3::CameraSensorViewConfiguration* p = view_configuration_;
  // @@protoc_insertion_point(field_get:osi3.CameraSensorView.view_configuration)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::CameraSensorViewConfiguration*>(
      &::osi3::_CameraSensorViewConfiguration_default_instance_);
}
inline ::osi3::CameraSensorViewConfiguration* CameraSensorView::release_view_configuration() {
  // @@protoc_insertion_point(field_release:osi3.CameraSensorView.view_configuration)
  
  ::osi3::CameraSensorViewConfiguration* temp = view_configuration_;
  view_configuration_ = NULL;
  return temp;
}
inline ::osi3::CameraSensorViewConfiguration* CameraSensorView::mutable_view_configuration() {
  
  if (view_configuration_ == NULL) {
    view_configuration_ = new ::osi3::CameraSensorViewConfiguration;
  }
  // @@protoc_insertion_point(field_mutable:osi3.CameraSensorView.view_configuration)
  return view_configuration_;
}
inline void CameraSensorView::set_allocated_view_configuration(::osi3::CameraSensorViewConfiguration* view_configuration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_configuration_);
  }
  if (view_configuration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      view_configuration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_configuration, submessage_arena);
    }
    
  } else {
    
  }
  view_configuration_ = view_configuration;
  // @@protoc_insertion_point(field_set_allocated:osi3.CameraSensorView.view_configuration)
}

// bytes image_data = 2;
inline void CameraSensorView::clear_image_data() {
  image_data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& CameraSensorView::image_data() const {
  // @@protoc_insertion_point(field_get:osi3.CameraSensorView.image_data)
  return image_data_.GetNoArena();
}
inline void CameraSensorView::set_image_data(const ::std::string& value) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:osi3.CameraSensorView.image_data)
}
#if LANG_CXX11
inline void CameraSensorView::set_image_data(::std::string&& value) {
  
  image_data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:osi3.CameraSensorView.image_data)
}
#endif
inline void CameraSensorView::set_image_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:osi3.CameraSensorView.image_data)
}
inline void CameraSensorView::set_image_data(const void* value, size_t size) {
  
  image_data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:osi3.CameraSensorView.image_data)
}
inline ::std::string* CameraSensorView::mutable_image_data() {
  
  // @@protoc_insertion_point(field_mutable:osi3.CameraSensorView.image_data)
  return image_data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* CameraSensorView::release_image_data() {
  // @@protoc_insertion_point(field_release:osi3.CameraSensorView.image_data)
  
  return image_data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void CameraSensorView::set_allocated_image_data(::std::string* image_data) {
  if (image_data != NULL) {
    
  } else {
    
  }
  image_data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), image_data);
  // @@protoc_insertion_point(field_set_allocated:osi3.CameraSensorView.image_data)
}

// -------------------------------------------------------------------

// UltrasonicSensorView

// .osi3.UltrasonicSensorViewConfiguration view_configuration = 1;
inline bool UltrasonicSensorView::has_view_configuration() const {
  return this != internal_default_instance() && view_configuration_ != NULL;
}
inline const ::osi3::UltrasonicSensorViewConfiguration& UltrasonicSensorView::view_configuration() const {
  const ::osi3::UltrasonicSensorViewConfiguration* p = view_configuration_;
  // @@protoc_insertion_point(field_get:osi3.UltrasonicSensorView.view_configuration)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::UltrasonicSensorViewConfiguration*>(
      &::osi3::_UltrasonicSensorViewConfiguration_default_instance_);
}
inline ::osi3::UltrasonicSensorViewConfiguration* UltrasonicSensorView::release_view_configuration() {
  // @@protoc_insertion_point(field_release:osi3.UltrasonicSensorView.view_configuration)
  
  ::osi3::UltrasonicSensorViewConfiguration* temp = view_configuration_;
  view_configuration_ = NULL;
  return temp;
}
inline ::osi3::UltrasonicSensorViewConfiguration* UltrasonicSensorView::mutable_view_configuration() {
  
  if (view_configuration_ == NULL) {
    view_configuration_ = new ::osi3::UltrasonicSensorViewConfiguration;
  }
  // @@protoc_insertion_point(field_mutable:osi3.UltrasonicSensorView.view_configuration)
  return view_configuration_;
}
inline void UltrasonicSensorView::set_allocated_view_configuration(::osi3::UltrasonicSensorViewConfiguration* view_configuration) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(view_configuration_);
  }
  if (view_configuration) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      view_configuration = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, view_configuration, submessage_arena);
    }
    
  } else {
    
  }
  view_configuration_ = view_configuration;
  // @@protoc_insertion_point(field_set_allocated:osi3.UltrasonicSensorView.view_configuration)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osi3

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_osi_5fsensorview_2eproto__INCLUDED
