// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: osi_roadmarking.proto

#ifndef PROTOBUF_osi_5froadmarking_2eproto__INCLUDED
#define PROTOBUF_osi_5froadmarking_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "osi_common.pb.h"
#include "osi_trafficsign.pb.h"
// @@protoc_insertion_point(includes)

namespace protobuf_osi_5froadmarking_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsRoadMarking_ClassificationImpl();
void InitDefaultsRoadMarking_Classification();
void InitDefaultsRoadMarkingImpl();
void InitDefaultsRoadMarking();
inline void InitDefaults() {
  InitDefaultsRoadMarking_Classification();
  InitDefaultsRoadMarking();
}
}  // namespace protobuf_osi_5froadmarking_2eproto
namespace osi3 {
class RoadMarking;
class RoadMarkingDefaultTypeInternal;
extern RoadMarkingDefaultTypeInternal _RoadMarking_default_instance_;
class RoadMarking_Classification;
class RoadMarking_ClassificationDefaultTypeInternal;
extern RoadMarking_ClassificationDefaultTypeInternal _RoadMarking_Classification_default_instance_;
}  // namespace osi3
namespace osi3 {

enum RoadMarking_Classification_Type {
  RoadMarking_Classification_Type_TYPE_UNKNOWN = 0,
  RoadMarking_Classification_Type_TYPE_OTHER = 1,
  RoadMarking_Classification_Type_TYPE_PAINTED_TRAFFIC_SIGN = 2,
  RoadMarking_Classification_Type_TYPE_SYMBOLIC_TRAFFIC_SIGN = 3,
  RoadMarking_Classification_Type_TYPE_TEXTUAL_TRAFFIC_SIGN = 4,
  RoadMarking_Classification_Type_TYPE_GENERIC_SYMBOL = 5,
  RoadMarking_Classification_Type_TYPE_GENERIC_LINE = 6,
  RoadMarking_Classification_Type_TYPE_GENERIC_TEXT = 7,
  RoadMarking_Classification_Type_RoadMarking_Classification_Type_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RoadMarking_Classification_Type_RoadMarking_Classification_Type_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RoadMarking_Classification_Type_IsValid(int value);
const RoadMarking_Classification_Type RoadMarking_Classification_Type_Type_MIN = RoadMarking_Classification_Type_TYPE_UNKNOWN;
const RoadMarking_Classification_Type RoadMarking_Classification_Type_Type_MAX = RoadMarking_Classification_Type_TYPE_GENERIC_TEXT;
const int RoadMarking_Classification_Type_Type_ARRAYSIZE = RoadMarking_Classification_Type_Type_MAX + 1;

const ::google::protobuf::EnumDescriptor* RoadMarking_Classification_Type_descriptor();
inline const ::std::string& RoadMarking_Classification_Type_Name(RoadMarking_Classification_Type value) {
  return ::google::protobuf::internal::NameOfEnum(
    RoadMarking_Classification_Type_descriptor(), value);
}
inline bool RoadMarking_Classification_Type_Parse(
    const ::std::string& name, RoadMarking_Classification_Type* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RoadMarking_Classification_Type>(
    RoadMarking_Classification_Type_descriptor(), name, value);
}
enum RoadMarking_Classification_Color {
  RoadMarking_Classification_Color_COLOR_UNKNOWN = 0,
  RoadMarking_Classification_Color_COLOR_OTHER = 1,
  RoadMarking_Classification_Color_COLOR_WHITE = 2,
  RoadMarking_Classification_Color_COLOR_YELLOW = 3,
  RoadMarking_Classification_Color_COLOR_BLUE = 5,
  RoadMarking_Classification_Color_COLOR_RED = 6,
  RoadMarking_Classification_Color_COLOR_GREEN = 7,
  RoadMarking_Classification_Color_COLOR_VIOLET = 8,
  RoadMarking_Classification_Color_RoadMarking_Classification_Color_INT_MIN_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32min,
  RoadMarking_Classification_Color_RoadMarking_Classification_Color_INT_MAX_SENTINEL_DO_NOT_USE_ = ::google::protobuf::kint32max
};
bool RoadMarking_Classification_Color_IsValid(int value);
const RoadMarking_Classification_Color RoadMarking_Classification_Color_Color_MIN = RoadMarking_Classification_Color_COLOR_UNKNOWN;
const RoadMarking_Classification_Color RoadMarking_Classification_Color_Color_MAX = RoadMarking_Classification_Color_COLOR_VIOLET;
const int RoadMarking_Classification_Color_Color_ARRAYSIZE = RoadMarking_Classification_Color_Color_MAX + 1;

const ::google::protobuf::EnumDescriptor* RoadMarking_Classification_Color_descriptor();
inline const ::std::string& RoadMarking_Classification_Color_Name(RoadMarking_Classification_Color value) {
  return ::google::protobuf::internal::NameOfEnum(
    RoadMarking_Classification_Color_descriptor(), value);
}
inline bool RoadMarking_Classification_Color_Parse(
    const ::std::string& name, RoadMarking_Classification_Color* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RoadMarking_Classification_Color>(
    RoadMarking_Classification_Color_descriptor(), name, value);
}
// ===================================================================

class RoadMarking_Classification : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.RoadMarking.Classification) */ {
 public:
  RoadMarking_Classification();
  virtual ~RoadMarking_Classification();

  RoadMarking_Classification(const RoadMarking_Classification& from);

  inline RoadMarking_Classification& operator=(const RoadMarking_Classification& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadMarking_Classification(RoadMarking_Classification&& from) noexcept
    : RoadMarking_Classification() {
    *this = ::std::move(from);
  }

  inline RoadMarking_Classification& operator=(RoadMarking_Classification&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadMarking_Classification& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoadMarking_Classification* internal_default_instance() {
    return reinterpret_cast<const RoadMarking_Classification*>(
               &_RoadMarking_Classification_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(RoadMarking_Classification* other);
  friend void swap(RoadMarking_Classification& a, RoadMarking_Classification& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadMarking_Classification* New() const PROTOBUF_FINAL { return New(NULL); }

  RoadMarking_Classification* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoadMarking_Classification& from);
  void MergeFrom(const RoadMarking_Classification& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoadMarking_Classification* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef RoadMarking_Classification_Type Type;
  static const Type TYPE_UNKNOWN =
    RoadMarking_Classification_Type_TYPE_UNKNOWN;
  static const Type TYPE_OTHER =
    RoadMarking_Classification_Type_TYPE_OTHER;
  static const Type TYPE_PAINTED_TRAFFIC_SIGN =
    RoadMarking_Classification_Type_TYPE_PAINTED_TRAFFIC_SIGN;
  static const Type TYPE_SYMBOLIC_TRAFFIC_SIGN =
    RoadMarking_Classification_Type_TYPE_SYMBOLIC_TRAFFIC_SIGN;
  static const Type TYPE_TEXTUAL_TRAFFIC_SIGN =
    RoadMarking_Classification_Type_TYPE_TEXTUAL_TRAFFIC_SIGN;
  static const Type TYPE_GENERIC_SYMBOL =
    RoadMarking_Classification_Type_TYPE_GENERIC_SYMBOL;
  static const Type TYPE_GENERIC_LINE =
    RoadMarking_Classification_Type_TYPE_GENERIC_LINE;
  static const Type TYPE_GENERIC_TEXT =
    RoadMarking_Classification_Type_TYPE_GENERIC_TEXT;
  static inline bool Type_IsValid(int value) {
    return RoadMarking_Classification_Type_IsValid(value);
  }
  static const Type Type_MIN =
    RoadMarking_Classification_Type_Type_MIN;
  static const Type Type_MAX =
    RoadMarking_Classification_Type_Type_MAX;
  static const int Type_ARRAYSIZE =
    RoadMarking_Classification_Type_Type_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Type_descriptor() {
    return RoadMarking_Classification_Type_descriptor();
  }
  static inline const ::std::string& Type_Name(Type value) {
    return RoadMarking_Classification_Type_Name(value);
  }
  static inline bool Type_Parse(const ::std::string& name,
      Type* value) {
    return RoadMarking_Classification_Type_Parse(name, value);
  }

  typedef RoadMarking_Classification_Color Color;
  static const Color COLOR_UNKNOWN =
    RoadMarking_Classification_Color_COLOR_UNKNOWN;
  static const Color COLOR_OTHER =
    RoadMarking_Classification_Color_COLOR_OTHER;
  static const Color COLOR_WHITE =
    RoadMarking_Classification_Color_COLOR_WHITE;
  static const Color COLOR_YELLOW =
    RoadMarking_Classification_Color_COLOR_YELLOW;
  static const Color COLOR_BLUE =
    RoadMarking_Classification_Color_COLOR_BLUE;
  static const Color COLOR_RED =
    RoadMarking_Classification_Color_COLOR_RED;
  static const Color COLOR_GREEN =
    RoadMarking_Classification_Color_COLOR_GREEN;
  static const Color COLOR_VIOLET =
    RoadMarking_Classification_Color_COLOR_VIOLET;
  static inline bool Color_IsValid(int value) {
    return RoadMarking_Classification_Color_IsValid(value);
  }
  static const Color Color_MIN =
    RoadMarking_Classification_Color_Color_MIN;
  static const Color Color_MAX =
    RoadMarking_Classification_Color_Color_MAX;
  static const int Color_ARRAYSIZE =
    RoadMarking_Classification_Color_Color_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor*
  Color_descriptor() {
    return RoadMarking_Classification_Color_descriptor();
  }
  static inline const ::std::string& Color_Name(Color value) {
    return RoadMarking_Classification_Color_Name(value);
  }
  static inline bool Color_Parse(const ::std::string& name,
      Color* value) {
    return RoadMarking_Classification_Color_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  // repeated .osi3.Identifier assigned_lane_id = 6;
  int assigned_lane_id_size() const;
  void clear_assigned_lane_id();
  static const int kAssignedLaneIdFieldNumber = 6;
  const ::osi3::Identifier& assigned_lane_id(int index) const;
  ::osi3::Identifier* mutable_assigned_lane_id(int index);
  ::osi3::Identifier* add_assigned_lane_id();
  ::google::protobuf::RepeatedPtrField< ::osi3::Identifier >*
      mutable_assigned_lane_id();
  const ::google::protobuf::RepeatedPtrField< ::osi3::Identifier >&
      assigned_lane_id() const;

  // string value_text = 5;
  void clear_value_text();
  static const int kValueTextFieldNumber = 5;
  const ::std::string& value_text() const;
  void set_value_text(const ::std::string& value);
  #if LANG_CXX11
  void set_value_text(::std::string&& value);
  #endif
  void set_value_text(const char* value);
  void set_value_text(const char* value, size_t size);
  ::std::string* mutable_value_text();
  ::std::string* release_value_text();
  void set_allocated_value_text(::std::string* value_text);

  // .osi3.TrafficSignValue value = 4;
  bool has_value() const;
  void clear_value();
  static const int kValueFieldNumber = 4;
  const ::osi3::TrafficSignValue& value() const;
  ::osi3::TrafficSignValue* release_value();
  ::osi3::TrafficSignValue* mutable_value();
  void set_allocated_value(::osi3::TrafficSignValue* value);

  // .osi3.RoadMarking.Classification.Type type = 1;
  void clear_type();
  static const int kTypeFieldNumber = 1;
  ::osi3::RoadMarking_Classification_Type type() const;
  void set_type(::osi3::RoadMarking_Classification_Type value);

  // .osi3.TrafficSign.MainSign.Classification.Type traffic_main_sign_type = 2;
  void clear_traffic_main_sign_type();
  static const int kTrafficMainSignTypeFieldNumber = 2;
  ::osi3::TrafficSign_MainSign_Classification_Type traffic_main_sign_type() const;
  void set_traffic_main_sign_type(::osi3::TrafficSign_MainSign_Classification_Type value);

  // .osi3.RoadMarking.Classification.Color monochrome_color = 3;
  void clear_monochrome_color();
  static const int kMonochromeColorFieldNumber = 3;
  ::osi3::RoadMarking_Classification_Color monochrome_color() const;
  void set_monochrome_color(::osi3::RoadMarking_Classification_Color value);

  // bool is_out_of_service = 7;
  void clear_is_out_of_service();
  static const int kIsOutOfServiceFieldNumber = 7;
  bool is_out_of_service() const;
  void set_is_out_of_service(bool value);

  // @@protoc_insertion_point(class_scope:osi3.RoadMarking.Classification)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::osi3::Identifier > assigned_lane_id_;
  ::google::protobuf::internal::ArenaStringPtr value_text_;
  ::osi3::TrafficSignValue* value_;
  int type_;
  int traffic_main_sign_type_;
  int monochrome_color_;
  bool is_out_of_service_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5froadmarking_2eproto::TableStruct;
  friend void ::protobuf_osi_5froadmarking_2eproto::InitDefaultsRoadMarking_ClassificationImpl();
};
// -------------------------------------------------------------------

class RoadMarking : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:osi3.RoadMarking) */ {
 public:
  RoadMarking();
  virtual ~RoadMarking();

  RoadMarking(const RoadMarking& from);

  inline RoadMarking& operator=(const RoadMarking& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  RoadMarking(RoadMarking&& from) noexcept
    : RoadMarking() {
    *this = ::std::move(from);
  }

  inline RoadMarking& operator=(RoadMarking&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadMarking& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RoadMarking* internal_default_instance() {
    return reinterpret_cast<const RoadMarking*>(
               &_RoadMarking_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(RoadMarking* other);
  friend void swap(RoadMarking& a, RoadMarking& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline RoadMarking* New() const PROTOBUF_FINAL { return New(NULL); }

  RoadMarking* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const RoadMarking& from);
  void MergeFrom(const RoadMarking& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(RoadMarking* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef RoadMarking_Classification Classification;

  // accessors -------------------------------------------------------

  // .osi3.Identifier id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::osi3::Identifier& id() const;
  ::osi3::Identifier* release_id();
  ::osi3::Identifier* mutable_id();
  void set_allocated_id(::osi3::Identifier* id);

  // .osi3.BaseStationary base = 2;
  bool has_base() const;
  void clear_base();
  static const int kBaseFieldNumber = 2;
  const ::osi3::BaseStationary& base() const;
  ::osi3::BaseStationary* release_base();
  ::osi3::BaseStationary* mutable_base();
  void set_allocated_base(::osi3::BaseStationary* base);

  // .osi3.RoadMarking.Classification classification = 3;
  bool has_classification() const;
  void clear_classification();
  static const int kClassificationFieldNumber = 3;
  const ::osi3::RoadMarking_Classification& classification() const;
  ::osi3::RoadMarking_Classification* release_classification();
  ::osi3::RoadMarking_Classification* mutable_classification();
  void set_allocated_classification(::osi3::RoadMarking_Classification* classification);

  // @@protoc_insertion_point(class_scope:osi3.RoadMarking)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::osi3::Identifier* id_;
  ::osi3::BaseStationary* base_;
  ::osi3::RoadMarking_Classification* classification_;
  mutable int _cached_size_;
  friend struct ::protobuf_osi_5froadmarking_2eproto::TableStruct;
  friend void ::protobuf_osi_5froadmarking_2eproto::InitDefaultsRoadMarkingImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// RoadMarking_Classification

// .osi3.RoadMarking.Classification.Type type = 1;
inline void RoadMarking_Classification::clear_type() {
  type_ = 0;
}
inline ::osi3::RoadMarking_Classification_Type RoadMarking_Classification::type() const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.type)
  return static_cast< ::osi3::RoadMarking_Classification_Type >(type_);
}
inline void RoadMarking_Classification::set_type(::osi3::RoadMarking_Classification_Type value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:osi3.RoadMarking.Classification.type)
}

// .osi3.TrafficSign.MainSign.Classification.Type traffic_main_sign_type = 2;
inline void RoadMarking_Classification::clear_traffic_main_sign_type() {
  traffic_main_sign_type_ = 0;
}
inline ::osi3::TrafficSign_MainSign_Classification_Type RoadMarking_Classification::traffic_main_sign_type() const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.traffic_main_sign_type)
  return static_cast< ::osi3::TrafficSign_MainSign_Classification_Type >(traffic_main_sign_type_);
}
inline void RoadMarking_Classification::set_traffic_main_sign_type(::osi3::TrafficSign_MainSign_Classification_Type value) {
  
  traffic_main_sign_type_ = value;
  // @@protoc_insertion_point(field_set:osi3.RoadMarking.Classification.traffic_main_sign_type)
}

// .osi3.RoadMarking.Classification.Color monochrome_color = 3;
inline void RoadMarking_Classification::clear_monochrome_color() {
  monochrome_color_ = 0;
}
inline ::osi3::RoadMarking_Classification_Color RoadMarking_Classification::monochrome_color() const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.monochrome_color)
  return static_cast< ::osi3::RoadMarking_Classification_Color >(monochrome_color_);
}
inline void RoadMarking_Classification::set_monochrome_color(::osi3::RoadMarking_Classification_Color value) {
  
  monochrome_color_ = value;
  // @@protoc_insertion_point(field_set:osi3.RoadMarking.Classification.monochrome_color)
}

// .osi3.TrafficSignValue value = 4;
inline bool RoadMarking_Classification::has_value() const {
  return this != internal_default_instance() && value_ != NULL;
}
inline const ::osi3::TrafficSignValue& RoadMarking_Classification::value() const {
  const ::osi3::TrafficSignValue* p = value_;
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.value)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::TrafficSignValue*>(
      &::osi3::_TrafficSignValue_default_instance_);
}
inline ::osi3::TrafficSignValue* RoadMarking_Classification::release_value() {
  // @@protoc_insertion_point(field_release:osi3.RoadMarking.Classification.value)
  
  ::osi3::TrafficSignValue* temp = value_;
  value_ = NULL;
  return temp;
}
inline ::osi3::TrafficSignValue* RoadMarking_Classification::mutable_value() {
  
  if (value_ == NULL) {
    value_ = new ::osi3::TrafficSignValue;
  }
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.Classification.value)
  return value_;
}
inline void RoadMarking_Classification::set_allocated_value(::osi3::TrafficSignValue* value) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(value_);
  }
  if (value) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, value, submessage_arena);
    }
    
  } else {
    
  }
  value_ = value;
  // @@protoc_insertion_point(field_set_allocated:osi3.RoadMarking.Classification.value)
}

// string value_text = 5;
inline void RoadMarking_Classification::clear_value_text() {
  value_text_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& RoadMarking_Classification::value_text() const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.value_text)
  return value_text_.GetNoArena();
}
inline void RoadMarking_Classification::set_value_text(const ::std::string& value) {
  
  value_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:osi3.RoadMarking.Classification.value_text)
}
#if LANG_CXX11
inline void RoadMarking_Classification::set_value_text(::std::string&& value) {
  
  value_text_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:osi3.RoadMarking.Classification.value_text)
}
#endif
inline void RoadMarking_Classification::set_value_text(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  value_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:osi3.RoadMarking.Classification.value_text)
}
inline void RoadMarking_Classification::set_value_text(const char* value, size_t size) {
  
  value_text_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:osi3.RoadMarking.Classification.value_text)
}
inline ::std::string* RoadMarking_Classification::mutable_value_text() {
  
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.Classification.value_text)
  return value_text_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoadMarking_Classification::release_value_text() {
  // @@protoc_insertion_point(field_release:osi3.RoadMarking.Classification.value_text)
  
  return value_text_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoadMarking_Classification::set_allocated_value_text(::std::string* value_text) {
  if (value_text != NULL) {
    
  } else {
    
  }
  value_text_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value_text);
  // @@protoc_insertion_point(field_set_allocated:osi3.RoadMarking.Classification.value_text)
}

// repeated .osi3.Identifier assigned_lane_id = 6;
inline int RoadMarking_Classification::assigned_lane_id_size() const {
  return assigned_lane_id_.size();
}
inline const ::osi3::Identifier& RoadMarking_Classification::assigned_lane_id(int index) const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.assigned_lane_id)
  return assigned_lane_id_.Get(index);
}
inline ::osi3::Identifier* RoadMarking_Classification::mutable_assigned_lane_id(int index) {
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.Classification.assigned_lane_id)
  return assigned_lane_id_.Mutable(index);
}
inline ::osi3::Identifier* RoadMarking_Classification::add_assigned_lane_id() {
  // @@protoc_insertion_point(field_add:osi3.RoadMarking.Classification.assigned_lane_id)
  return assigned_lane_id_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::osi3::Identifier >*
RoadMarking_Classification::mutable_assigned_lane_id() {
  // @@protoc_insertion_point(field_mutable_list:osi3.RoadMarking.Classification.assigned_lane_id)
  return &assigned_lane_id_;
}
inline const ::google::protobuf::RepeatedPtrField< ::osi3::Identifier >&
RoadMarking_Classification::assigned_lane_id() const {
  // @@protoc_insertion_point(field_list:osi3.RoadMarking.Classification.assigned_lane_id)
  return assigned_lane_id_;
}

// bool is_out_of_service = 7;
inline void RoadMarking_Classification::clear_is_out_of_service() {
  is_out_of_service_ = false;
}
inline bool RoadMarking_Classification::is_out_of_service() const {
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.Classification.is_out_of_service)
  return is_out_of_service_;
}
inline void RoadMarking_Classification::set_is_out_of_service(bool value) {
  
  is_out_of_service_ = value;
  // @@protoc_insertion_point(field_set:osi3.RoadMarking.Classification.is_out_of_service)
}

// -------------------------------------------------------------------

// RoadMarking

// .osi3.Identifier id = 1;
inline bool RoadMarking::has_id() const {
  return this != internal_default_instance() && id_ != NULL;
}
inline const ::osi3::Identifier& RoadMarking::id() const {
  const ::osi3::Identifier* p = id_;
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.id)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::Identifier*>(
      &::osi3::_Identifier_default_instance_);
}
inline ::osi3::Identifier* RoadMarking::release_id() {
  // @@protoc_insertion_point(field_release:osi3.RoadMarking.id)
  
  ::osi3::Identifier* temp = id_;
  id_ = NULL;
  return temp;
}
inline ::osi3::Identifier* RoadMarking::mutable_id() {
  
  if (id_ == NULL) {
    id_ = new ::osi3::Identifier;
  }
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.id)
  return id_;
}
inline void RoadMarking::set_allocated_id(::osi3::Identifier* id) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(id_);
  }
  if (id) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      id = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, id, submessage_arena);
    }
    
  } else {
    
  }
  id_ = id;
  // @@protoc_insertion_point(field_set_allocated:osi3.RoadMarking.id)
}

// .osi3.BaseStationary base = 2;
inline bool RoadMarking::has_base() const {
  return this != internal_default_instance() && base_ != NULL;
}
inline const ::osi3::BaseStationary& RoadMarking::base() const {
  const ::osi3::BaseStationary* p = base_;
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.base)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::BaseStationary*>(
      &::osi3::_BaseStationary_default_instance_);
}
inline ::osi3::BaseStationary* RoadMarking::release_base() {
  // @@protoc_insertion_point(field_release:osi3.RoadMarking.base)
  
  ::osi3::BaseStationary* temp = base_;
  base_ = NULL;
  return temp;
}
inline ::osi3::BaseStationary* RoadMarking::mutable_base() {
  
  if (base_ == NULL) {
    base_ = new ::osi3::BaseStationary;
  }
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.base)
  return base_;
}
inline void RoadMarking::set_allocated_base(::osi3::BaseStationary* base) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete reinterpret_cast< ::google::protobuf::MessageLite*>(base_);
  }
  if (base) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      base = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, base, submessage_arena);
    }
    
  } else {
    
  }
  base_ = base;
  // @@protoc_insertion_point(field_set_allocated:osi3.RoadMarking.base)
}

// .osi3.RoadMarking.Classification classification = 3;
inline bool RoadMarking::has_classification() const {
  return this != internal_default_instance() && classification_ != NULL;
}
inline void RoadMarking::clear_classification() {
  if (GetArenaNoVirtual() == NULL && classification_ != NULL) {
    delete classification_;
  }
  classification_ = NULL;
}
inline const ::osi3::RoadMarking_Classification& RoadMarking::classification() const {
  const ::osi3::RoadMarking_Classification* p = classification_;
  // @@protoc_insertion_point(field_get:osi3.RoadMarking.classification)
  return p != NULL ? *p : *reinterpret_cast<const ::osi3::RoadMarking_Classification*>(
      &::osi3::_RoadMarking_Classification_default_instance_);
}
inline ::osi3::RoadMarking_Classification* RoadMarking::release_classification() {
  // @@protoc_insertion_point(field_release:osi3.RoadMarking.classification)
  
  ::osi3::RoadMarking_Classification* temp = classification_;
  classification_ = NULL;
  return temp;
}
inline ::osi3::RoadMarking_Classification* RoadMarking::mutable_classification() {
  
  if (classification_ == NULL) {
    classification_ = new ::osi3::RoadMarking_Classification;
  }
  // @@protoc_insertion_point(field_mutable:osi3.RoadMarking.classification)
  return classification_;
}
inline void RoadMarking::set_allocated_classification(::osi3::RoadMarking_Classification* classification) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete classification_;
  }
  if (classification) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      classification = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, classification, submessage_arena);
    }
    
  } else {
    
  }
  classification_ = classification;
  // @@protoc_insertion_point(field_set_allocated:osi3.RoadMarking.classification)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace osi3

namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::osi3::RoadMarking_Classification_Type> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::osi3::RoadMarking_Classification_Type>() {
  return ::osi3::RoadMarking_Classification_Type_descriptor();
}
template <> struct is_proto_enum< ::osi3::RoadMarking_Classification_Color> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::osi3::RoadMarking_Classification_Color>() {
  return ::osi3::RoadMarking_Classification_Color_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_osi_5froadmarking_2eproto__INCLUDED
